---
title: "Untitled"
output: html_document
---

```{r}
library(tidyverse)
library(gtsummary)
library(survey)
library(RColorBrewer)
library(sf)
library(haven)

```


```{r}
consulta_endes <- function(periodo, codigo_modulo, base, guardar = FALSE, ruta = "", codificacion=NULL) {
  # Generamos dos objetos temporales: un archivo y una carpeta 
  temp <- tempfile() ; tempdir <- tempdir()
  
  # Genera una matriz con el número identificador de versiones por cada año
  versiones <- matrix(c(2022,786,2021,760,2020, 739, 2019, 691, 
                        2018, 638, 2017,605,2016,548,2015,504,2014,441,
                        2013,407,2012,323,2011,290,2010,260,
                        2009,238,2008,209,2007,194,2006,183,
                        2005,150,2004,120),byrow = T,ncol = 2)
  
  # Extrae el código de la encuesta con la matriz versiones
  codigo_encuesta <- versiones[versiones[,1] == periodo,2]
  ruta_base <- "http://proyectos.inei.gob.pe/iinei/srienaho/descarga/SPSS/" # La ruta de microdatos INEI
  modulo <- paste("-Modulo",codigo_modulo,".zip",sep = "")
  url <- paste(ruta_base,codigo_encuesta,modulo,sep = "")
  
  # Descargamos el archivo
  utils::download.file(url,temp)
  
  # Listamos los archivos descargados y seleccionamos la base elegida
  archivos <- utils::unzip(temp,list = T)
  archivos <- archivos[stringr::str_detect(archivos$Name, paste0(base,"\\.")) == TRUE,]
  
  # Elegimos entre guardar los archivos o pasarlos directamente a un objeto
  if(guardar == TRUE) {
    utils::unzip(temp, files = archivos$Name, exdir = paste(getwd(), "/", ruta, sep = ""))
    print(paste("Archivos descargados en: ", getwd(), "/", ruta, sep = ""))
  } 
  else {
    endes <- haven::read_sav(
      utils::unzip(
        temp, 
        files = archivos$Name[grepl(".sav|.SAV",archivos$Name)], 
        exdir = tempdir
        ), 
      encoding = codificacion
      )
    nombres <- toupper(colnames(endes))
    colnames(endes) <- nombres
    endes
  }
}



```

# 2022

```{r}
rec43<-consulta_endes(periodo = 2022, codigo_modulo = 1634, base = "REC43", guardar = F)# eda
rech23<-consulta_endes(periodo = 2022, codigo_modulo = 1630, base = "RECH23", guardar = F)# mediador
rec0111<-consulta_endes(periodo = 2022, codigo_modulo = 1631, base = "REC0111", guardar = F)#otras variables
rech0<-consulta_endes(periodo = 2022, codigo_modulo = 1629, base = "RECH0", guardar = F)# meses

```

```{r}
MOV2022<-
  rec43 %>% 
  mutate(
    HHID = as.numeric(str_sub(CASEID,1,-3))
  ) %>% 
  
  left_join(

rec0111 %>% 
  mutate(
    HHID = as.numeric(str_sub(CASEID,1,-3))
  )
) %>% 
  
left_join(rech0 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  left_join(rech23 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(
    mes = HV008 - ((ID1-1900)*12),
    ANIO = 2022
  )

```

# 2021

```{r}
rec43<-consulta_endes(periodo = 2021, codigo_modulo = 1634, base = "REC43", guardar = F)# eda
rech23<-consulta_endes(periodo = 2021, codigo_modulo = 1630, base = "RECH23", guardar = F)# mediador
rec0111<-consulta_endes(periodo = 2021, codigo_modulo = 1631, base = "REC0111", guardar = F)#otras variables
rech0<-consulta_endes(periodo = 2021, codigo_modulo = 1629, base = "RECH0", guardar = F)# meses

```

```{r}
MOV2021<-
  rec43 %>% 
  mutate(
    HHID = as.numeric(str_sub(CASEID,1,-3))
  ) %>% 
  
  left_join(

rec0111 %>% 
  mutate(
    HHID = as.numeric(str_sub(CASEID,1,-3))
  )
) %>% 
  
left_join(rech0 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  left_join(rech23 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(
    mes = HV008 - ((ID1-1900)*12),
    ANIO = 2021
  ) 

```

# MOV 2020

```{r}
#NINIO <- read.csv("ENDES/2020/DIT.csv", sep = ";" )
NINIO2 <- read.csv("ENDES/2020/REC41.csv", sep = ";" )
MUJER1 <- read.csv("ENDES/2020/REC42.csv", sep = ";" )
VACUNA1 <- read.csv("ENDES/2020/REC43.csv", sep = ";" )
VACUNA2 <- read.csv("ENDES/2020/REC95.csv", sep = ";" )
HOGAR1 <- read.csv("ENDES/2020/RECH0.csv", sep = ";" )
HOGAR_MADRE <- read.csv("ENDES/2020/RECH1.csv", sep = ";" )
VIVIENDA1 <- read.csv("ENDES/2020/RECH23.csv", sep = ";" )
MUJER2<- read.csv("ENDES/2020/REC0111.csv", sep = ";" )
MUJER3<- read_sav("ENDES/2020/Programas Sociales x Hogar.sav")
NINIO_ANEMIA<- read.csv("ENDES/2020/RECH6.csv", sep = ";" )
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")

#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))


MUJER3<-MUJER3 %>% 
  
  mutate(JUNTOS = ifelse(QH95 == 1, 1,0),
         HHID = as.numeric(HHID)) %>% 
  select(-QH95)


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2020<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(ANIO = 2020,
         mes = HV008 - ((ID1-1900)*12))




```


# 2019
```{r}
#NINIO <- haven::read_sav("ENDES/2019/DIT.sav")
NINIO2 <- read_sav("ENDES/2019/REC41.sav")
MUJER1 <- read_sav("ENDES/2019/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2019/REC43.sav")
VACUNA2 <- read_sav("ENDES/2019/REC95.sav")
HOGAR1 <- read_sav("ENDES/2019/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2019/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2019/RECH23.sav")
MUJER2<- read_sav("ENDES/2019/REC0111.sav")
MUJER3<- read_sav("ENDES/2019/Programas Sociales x Hogar.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")

#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>%
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))


MUJER3<-MUJER3 %>% 
  
  mutate(JUNTOS = ifelse(QH95 == 1, 1,0),
         HHID = as.numeric(HHID)) %>% 
  select(-QH95)


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2019<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>%  

  
  mutate(ANIO = 2019,
         mes = HV008 - ((ID1-1900)*12))

```
#2018

```{r}
#NINIO <- haven::read_sav("./ENDES/2018/DIT.sav")
NINIO2 <- read_sav("ENDES/2018/REC41.sav")
MUJER1 <- read_sav("ENDES/2018/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2018/REC43.sav")
VACUNA2 <- read_sav("ENDES/2018/REC95.sav")
HOGAR1 <- read_sav("ENDES/2018/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2018/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2018/RECH23.sav")
MUJER2<- read_sav("ENDES/2018/REC0111.sav")
MUJER3<- read_sav("ENDES/2018/Programas Sociales x Hogar.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")

#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))


MUJER3<-MUJER3 %>% 
  
  mutate(JUNTOS = ifelse(QH95 == 1, 1,0),
         HHID = as.numeric(HHID)) %>% 
  select(-QH95)


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2018<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(ANIO = 2018,
         mes = HV008 - ((2018-1900)*12))



```

# 2017

```{r}

NINIO2 <- read_sav("ENDES/2017/REC41.sav")
MUJER1 <- read_sav("ENDES/2017/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2017/REC43.sav")
VACUNA2 <- read_sav("ENDES/2017/REC95.sav")
HOGAR1 <- read_sav("ENDES/2017/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2017/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2017/RECH23.sav")
MUJER2<- read_sav("ENDES/2017/REC0111.sav")
MUJER3<- read_sav("ENDES/2017/Programas Sociales x Hogar.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")

#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))


MUJER3<-MUJER3 %>% select(HHID,QH95) %>% 
  
  mutate(JUNTOS = ifelse(QH95 == 1, 1,0),
         HHID = as.numeric(HHID)) %>% 
  select(-QH95)


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2017<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>%  
  
  mutate(ANIO = 2017,
         mes = HV008 - ((2017-1900)*12))

```

# 2016

```{r}
#NINIO <- haven::read_sav("ENDES/2016/DIT.sav")
NINIO2 <- read_sav("ENDES/2016/REC41.sav")
MUJER1 <- read_sav("ENDES/2016/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2016/REC43.sav")
VACUNA2 <- read_sav("ENDES/2016/REC95.sav")
HOGAR1 <- read_sav("ENDES/2016/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2016/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2016/RECH23.sav")
MUJER2<- read_sav("ENDES/2016/REC0111.sav")
MUJER3<- read_sav("ENDES/2016/Programas Sociales x Hogar.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")
#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         V005 = v005) %>% 
  select(-v005)


MUJER3<-MUJER3 %>% 
  
  mutate(JUNTOS = ifelse(QH95 == 1, 1,0),
         HHID = as.numeric(HHID)) %>% 
  select(-QH95)


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2016<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(ANIO = 2016,
         mes = HV008 - ((2016-1900)*12))


```

# 2015

```{r}
#NINIO <- haven::read_sav("ENDES/2015/DIT.sav")
NINIO2 <- read_sav("ENDES/2015/REC41.sav")
MUJER1 <- read_sav("ENDES/2015/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2015/REC43.sav")
VACUNA2 <- haven::read_sav("ENDES/2015/REC95.sav") # EDAD
HOGAR1 <- read_sav("ENDES/2015/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2015/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2015/RECH23.sav")
MUJER2<- read_sav("ENDES/2015/REC0111.sav")
MUJER3<- read_sav("ENDES/2015/Programas Sociales x Hogar.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")
#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))


MUJER3<-MUJER3 %>% 
  
  mutate(JUNTOS = ifelse(QH95 == 1, 1,0),
         HHID = as.numeric(HHID)) %>% 
  select(-QH95)


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2015<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(ANIO = 2015,
         mes = HV008 - ((2015-1900)*12))




```

# 2014

```{r}
#NINIO <- haven::read_sav("ENDES/2014/DIT.sav")
NINIO2 <- read_sav("ENDES/2014/REC41.sav")
MUJER1 <- read_sav("ENDES/2014/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2014/REC43.sav")
VACUNA2 <- read_sav("ENDES/2014/REC95.sav")
HOGAR1 <- read_sav("ENDES/2014/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2014/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2014/RECH23.sav")
MUJER2<- read_sav("ENDES/2014/REC0111.sav")
MUJER3<- read_sav("ENDES/2014/Programas Sociales x Hogar.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")
#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         V005 = v005) %>% 
  select(-v005)


MUJER3<-MUJER3 %>% 
  
  mutate(JUNTOS = ifelse(QH95 == 1, 1,0),
         HHID = as.numeric(HHID)) %>% 
  select(-QH95)


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2014<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(
    ANIO = 2014,
    mes = HV008 - ((2014-1900)*12)) 
  


```

# 2013

```{r}
#NINIO <- haven::read_sav("ENDES/2013/DIT.sav")
NINIO2 <- read_sav("ENDES/2013/REC41.sav")
MUJER1 <- read_sav("ENDES/2013/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2013/REC43.sav")
VACUNA2 <- read_sav("ENDES/2013/REC95.sav")
HOGAR1 <- read_sav("ENDES/2013/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2013/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2013/RECH23.sav")
MUJER2<- read_sav("ENDES/2013/REC0111.sav")
MUJER3<- read_sav("ENDES/2013/REC91.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")
#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         V481X = v481x) %>% 
  select(-v481x)



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))


MUJER3<-MUJER3 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         JUNTOS = ifelse(S484 == 1 | S484 == 2,1,0),
         JUNTOS = 0)


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID","CASEID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2013<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(
    ANIO = 2013,
    mes = HV008 - ((2013-1900)*12),)

```

# 2012

```{r}
#NINIO <- haven::read_sav("ENDES/2012/DIT.sav")
NINIO2 <- read_sav("ENDES/2012/REC41.sav")
MUJER1 <- read_sav("ENDES/2012/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2012/REC43.sav")
VACUNA2 <- read_sav("ENDES/2012/REC95.sav")
HOGAR1 <- read_sav("ENDES/2012/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2012/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2012/RECH23.sav")
MUJER2<- read_sav("ENDES/2012/REC0111.sav")
MUJER3<- read_sav("ENDES/2012/REC91.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")
#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))


MUJER3<-MUJER3 %>% select(CASEID,SREGION,S108N,S484) %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         JUNTOS = ifelse(S484 == 1 | S484 == 2,1,0))


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID","CASEID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2012<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(
    ANIO = 2012,
    mes = HV008 - ((2012-1900)*12),) 


```


# 2011

```{r}
#NINIO <- haven::read_sav("ENDES/2011/DIT.sav")
NINIO2 <- read_sav("ENDES/2011/REC41.sav")
MUJER1 <- read_sav("ENDES/2011/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2011/REC43.sav")
VACUNA2 <- read_sav("ENDES/2011/REC95.sav")
HOGAR1 <- read_sav("ENDES/2011/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2011/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2011/RECH23.sav")
MUJER2<- read_sav("ENDES/2011/REC0111.sav")
MUJER3<- read_sav("ENDES/2011/REC91.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")
#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))


MUJER3<-MUJER3 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         JUNTOS = ifelse(S484 == 1 | S484 == 2,1,0))


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID","CASEID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2011<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(ANIO = 2011,
         mes = HV008 - ((2011-1900)*12),) 




```

# 2010

```{r}
NINIO2 <- read_sav("ENDES/2010/REC41.sav")
MUJER1 <- read_sav("ENDES/2010/REC42.sav" )
VACUNA1 <- read_sav("ENDES/2010/REC43.sav")
VACUNA2 <- read_sav("ENDES/2010/REC95.sav")
HOGAR1 <- read_sav("ENDES/2010/RECH0.sav")
HOGAR_MADRE <- read_sav("ENDES/2010/RECH1.sav")
VIVIENDA1 <- read_sav("ENDES/2010/RECH23.sav")
MUJER2<- read_sav("ENDES/2010/REC0111.sav")
MUJER3<- read_sav("ENDES/2010/REC91.sav")
region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")
#
# BD principales

## HHID Y HIDX son las variables de union 

VACUNA1<- VACUNA1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))

VACUNA2 <- VACUNA2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = IDX95) 


# Otras BD


## HHID Y HIDX son las variables de union 

# NINIO <- NINIO %>% select(CASEID,QI478,BIDX,BORD) %>% 
#   
#   mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
#          
#          HIDX = BIDX) 


NINIO2 <- NINIO2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         HIDX = MIDX) 



MUJER1<- MUJER1 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))



MUJER2<-MUJER2 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)))


MUJER3<-MUJER3 %>% 
  
  mutate(HHID = as.numeric(str_sub(CASEID,1,-3)),
         
         JUNTOS = ifelse(S484 == 1 | S484 == 2,1,0))


HOGAR_MADRE<-HOGAR_MADRE %>% 
  
  mutate(HIDX = HVIDX,
         HHID = as.integer(HHID))

## BD intermedias
VACUNA3 <- VACUNA1 %>% full_join(VACUNA2, by =c("HHID","HIDX","CASEID")) # Union tomando CASEID para no perder casos

#NINIO_3 <- NINIO %>% left_join(NINIO2, by = c("HHID","HIDX","CASEID"))



MUJER_4 <- MUJER1 %>% 
  
  left_join(MUJER2, by = c("HHID","CASEID")) %>%
  left_join(MUJER3, by = c("HHID","CASEID")) %>% 
  mutate(HIDX = as.numeric(str_sub(CASEID,-2,-1))) %>% 
  
  left_join(HOGAR_MADRE, by = c("HHID","HIDX"))


## BD final
MOV2010<- VACUNA3 %>% 
  
  left_join(NINIO2, by = c("HHID","HIDX","CASEID")) %>% 
  
  left_join(MUJER_4, by = c("HHID","CASEID"))  %>% 
  
  left_join(VIVIENDA1 %>% mutate(HHID = as.numeric(HHID))) %>% 
  
  left_join(HOGAR1 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(
    mes = HV008 - ((2010-1900)*12),
    ANIO = 2010) 

```



# 2009

```{r}
rec43<-consulta_endes(periodo = 2009, codigo_modulo = 70, base = "REC43", guardar = F)# eda
rech23<-consulta_endes(periodo = 2009, codigo_modulo = 65, base = "RECH23", guardar = F)# mediador
rec0111<-consulta_endes(periodo = 2009, codigo_modulo = 66, base = "REC0111", guardar = F)#otras variables
rech0<-consulta_endes(periodo = 2009, codigo_modulo = 64, base = "RECH0", guardar = F)# meses

```

```{r}
MOV2009<-
  rec43 %>% 
  mutate(
    HHID = as.numeric(str_sub(CASEID,1,-3))
  ) %>% 
  
  left_join(

rec0111 %>% 
  mutate(
    HHID = as.numeric(str_sub(CASEID,1,-3))
  )
) %>% 
  
  left_join(rech0 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  left_join(rech23 %>% mutate(HHID=as.numeric(HHID))) %>% 
  
  mutate(
    mes = HV008 - ((2009-1900)*12),
    ANIO = 2009
  ) %>% 
  select(ANIO,mes,CASEID,HHID,H11,HV201,HV205,HV225,HV237,HV008)

```

```{r}
list<- list(MOV2010,MOV2011,MOV2012,
            MOV2013,MOV2014,MOV2015,
            MOV2016,MOV2017,MOV2018,
            MOV2019,MOV2020,MOV2021,
            MOV2022)

mov_general<-map_df(.x = list,
                    
                    .f =
                      ~.x %>% 
                      select(ANIO,mes,CASEID,HHID,H11,HV201,HV205,HV225,HV237,HV008,
                             V012,V102,V106,V190))


write.csv(mov_general,"./NewData/mov_general2023.csv",row.names = F)

```




```{r}
list<- list(MOV2010,MOV2011,MOV2012,
            MOV2013,MOV2014,MOV2015,
            MOV2016,MOV2017,MOV2018,
            MOV2019,MOV2020)

mov_general<-map_df(.x = list, .f=~prep.data(MOV2020 = .x))

write.csv(mov_general,"./BD.INTERMEDIAS/mov_general.csv",row.names = F)

rm(list=ls())

```

