---
title: "MOV 1"
author: "jose"
date: "18/6/2021"
output:
  html_document:
    code_folding: hide
    fig_height: 6
    fig_width: 9
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

# Bases

```{r, echo=F, warning=F, message=F, error=F}
library(tidyverse)
library(gtsummary)
library(survey)
library(RColorBrewer)
library(sf)

region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")
```


# EDITAR BASES

```{r,warning=F, message=F, error=F}
prep.data <-function(MOV2020){ MOV2020 %>%
  
  select(CASEID,
         # H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,
         # S45D4,S45D5,S45P4,S45P5,S45B0,S45B1,
         # S45B2,S45B3,S45TT,S45SP1,S45SP2,S45SR,
         S45F1,S45F2,S45F3,
         S45PV1,S45PV2,S45PV3,
         S45NM1,S45NM2,S45NM3,
         S45RT1,S45RT2,
         S45IF1,S45IF2,
         
         S466,S466B,V001,V005,V012,V022,V023,
         V024,V025,V102,V106,V131,
         V481:V481X,V190,V022,ANIO) %>% 
  
  
  
  
        # cATEGORIAS DE RESPUESTA A LA VACUNACION
  mutate(
    
        across(S45F1:S45IF2,~ifelse(.x == 0|.x == 8,0, # 0: No, 8: No sabe
                                 ifelse(.x == 1|.x == 3,1,2))),# 1: Tarjeta fecha, # 3: Marca tarjeta

    
    
         
         CRED = as.factor(ifelse(S466==0 | S466 == 8,"No","Si")),
        
        
         
         S466B = ifelse(is.na(S466B),99,S466B),
         CREDLUGAR = factor(S466B, levels = c(21,22,23,24,
                                              25,26,27,31,
                                              32,41,42,96,99), labels = c("H.MINSA/FFAA","H.ESSALUD","H.MINSA/FFAA",
                                                                 "CS/POSTA MINSA","CS/POSTA MINSA","CS.ESSALUD",
                                                                 "OTRO/PRIVADO","OTRO/PRIVADO","OTRO/PRIVADO","OTRO/PRIVADO",
                                                                 "OTRO/PRIVADO","OTRO/PRIVADO","NoCRED")),
         
        
         
         
         TIPORESIDENCIA = ifelse(V102==1,"URBANO","RURAL"),
         
         
         
         
         
         DEPARTAMEN = factor(V024, levels = c(1:25), labels = c("AMAZONAS","ANCASH","APURIMAC","AREQUIPA","AYACUCHO",
                                                            "CAJAMARCA","CALLAO","CUSCO","HUANCAVELICA","HUANUCO",
                                                            "ICA","JUNIN","LA LIBERTAD","LAMBAYEQUE","LIMA",
                                                            "LORETO","MADRE DE DIOS","MOQUEGUA","PASCO","PIURA",
                                                            "PUNO","SAN MARTIN","TACNA","TUMBES","UCAYALI")),
         
         
         
         EDU_MADRE = factor(V106, levels = c(0,1,2,3), labels = c("sin educ","primaria","secundaria","superior")),
         
         
         ETNIA_MADRE = factor(V131, levels = c(1:12), labels = c("quechua","aimara","ashaninka","awajun",
                                                                 "shipibo","shawi","matsigenka","achuar",
                                                                 "Otro","castellano","portugues","Otro extranjero")),
         
         
         
         #EDAD_ANIOS = round((QI478/12),0),
         
         SEGURO = factor(V481, levels = c(0,1), labels = c("No","Si")),
         
         EDAD_MADRE = ifelse(V012<18,"< 18 a",
                             ifelse(V012>=18&V012<30,"18-30 a",
                                    ifelse(V012>=30&V012<40,"30 a 40",
                                           ifelse(V012>=40,"40 a mas",NA)))),
         
         INDICERIQUEZA = factor(V190, levels = c(1:5), labels = c("1ro","2do","3ro","4to","5to")),
    
    
        V005 = V005/1000000) %>% 
  
  
  fastDummies::dummy_cols(select_columns = c("S45F1","S45F2","S45F3", # Hib
                                             "S45PV1","S45PV2","S45PV3", #Pentavalente
                                             "S45NM1","S45NM2","S45NM3", #Neumococo
                                             "S45IF1","S45IF2", #Influenza
                                             "S45RT1","S45RT2" # Rotavirus
                                             
                                             )) %>% 
  
   # CON CRED O SEGURO
   filter((CRED == "Si" | SEGURO == "Si")) %>% 
  
  
  
  mutate( HIB_COMPLETA = as.factor(ifelse(S45F1 !=0 & S45F2 != 0 & S45F3 != 0,1,0)), # VACUNAS COMPLETAS
          PTV_COMPLETA = as.factor(ifelse(S45PV1 !=0 & S45PV2 != 0 & S45PV3 != 0,1,0)),
          NEUMO_COMPLETA = as.factor(ifelse(S45NM1 !=0 & S45NM2 != 0 & S45NM3 != 0,1,0)),
          INFLU_COMPLETA = as.factor(ifelse(S45IF1 !=0 & S45IF2 != 0,1,0)),
          ROTA_COMPLETA = as.factor(ifelse(S45RT1 !=0 & S45RT2 != 0,1,0)),
          
          
          #EDAD_CAT_V = ifelse(QI478 <12,"menor 1a","> 1 a"),
          
          
          # Inicio de esquemas 
          ## Pentavalente
          # MOV_PTV_e1 = ifelse(QI478<12 & S45PV1==0,1,0),
          # MOV_PTV_e2 = ifelse(QI478>12 & S45PV1==0,1,0),
          # MOV_PTV_e1_2= ifelse(MOV_PTV_e1 ==1 | MOV_PTV_e2 == 1,1,0),
          # 
          # ## Neumococo 
          # MOV_NEUMO_e1 = ifelse(QI478<12 & S45NM1==0,1,0),
          # MOV_NEUMO_e2 = ifelse(QI478>12 & S45NM1==0,1,0),
          # MOV_NEUMO_e1_2 = ifelse(MOV_NEUMO_e1==1 | MOV_NEUMO_e2==1,1,0),
          # 
          # ## Rotavirus (entre 2 y 4 meses, maximo 7 meses la 2da dosis)
          # MOV_ROTA_e1 = ifelse(QI478>8 & S45RT2 == 0,1,0),
          # 
          # ## INFLUENZA (<12 m : 2 dosis, 12-35 meses:1 dosis, >36 meses: 1 dosis adulto)
          # 
          # MOV_INFLU_e1 = ifelse(S45NM1 == 0,1,0),
          # MOV_INFLU_e2 = ifelse(QI478>12 & S45NM1 == 0,1,0),
          # MOV_INFLU_e1_2 = ifelse(MOV_INFLU_e1 == 1 | MOV_INFLU_e2==1, 1,0),
         
           ####
          MOV_PTV_e1 = ifelse(S45PV1==0,1,0),
          
          
          ## Neumococo 
          MOV_NEUMO_e1 = ifelse(S45NM1==0,1,0),
          
          
          ## Rotavirus (entre 2 y 4 meses, maximo 7 meses la 2da dosis)
          MOV_ROTA_e1 = ifelse(S45RT2 == 0,1,0),
          
          ## INFLUENZA (<12 m : 2 dosis, 12-35 meses:1 dosis, >36 meses: 1 dosis adulto)
          
          MOV_INFLU_e1 = ifelse(S45NM2 == 0,1,0))
          
}

```

# RESUMEN

V001 : CONGLOMERADO V022 : ESTRATO V005 : FACTOR DE PONDERACION MUJER

```{r,warning=F, message=F, error=F}

# Eliminando bases que no se usan
rm(list=ls())

# Base de trabajo
MOV_GENERAL <- read.csv("./BD.INTERMEDIAS/mov_general.csv")

df2<-MOV_GENERAL %>% 
  
  group_by(ANIO) %>% 
  nest() %>%
  mutate(
    df= map(.x = data, 
      .f = ~svydesign(id =~ V001, strata =~ V022, probs=~V005, data=.x))) 


#BD en survey
# df <- svydesign(id =~ V001, strata =~ V022, probs=~V005, data=MOV2020_2) 


options(survey.lonely.psu="remove")
# options(survey.adjust.domain.lonely=TRUE)
# options(survey.lonely.psu="adjust")

```

# PROPORCIONES POR REGIONES (GRAFICO)

```{r, echo=F, warning=F, message=F, error=F, fig.height= 10, fig.width= 10}

df3<-df2 %>% 
  
  mutate(
    ptv = map(.x = df , 
                 .f = ~svyby(~MOV_PTV_e1, by=~DEPARTAMEN, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV_COMPLETA") %>% 
                select(-`se.as.numeric(MOV_PTV_e1)`,-MOV_PTV_e1) %>% data.frame),
    
    neumo = map(.x = df , 
                 .f = ~svyby(~MOV_NEUMO_e1, by=~DEPARTAMEN, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                  
                  mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO_COMPLETA") %>% 
                  select(-`se.as.numeric(MOV_NEUMO_e1)`,-MOV_NEUMO_e1) %>% data.frame),
    
    influ = map(.x = df , 
                 .f = ~svyby(~MOV_INFLU_e1, by=~DEPARTAMEN, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                  
                  mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU_COMPLETA") %>%
                  select(-`se.as.numeric(MOV_INFLU_e1)`,-MOV_INFLU_e1) %>% data.frame),
    
    rota = map(.x = df , 
                 .f = ~svyby(~MOV_ROTA_e1, by=~DEPARTAMEN, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                 
                 mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA_COMPLETA") %>%
                 select(-`se.as.numeric(MOV_ROTA_e1)`,-MOV_ROTA_e1) %>% data.frame) ) %>%
  
  select(-data) %>% 
  
  mutate(
  
  pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
  pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
  
  total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
  
) %>% 
  
  select(ANIO,total) %>% 
  
  ungroup() %>% 
  
  unnest(cols = c(total)) %>% 
  
  full_join(region_shape, by="DEPARTAMEN") %>% 
  
  mutate(ANIO = as.character(ANIO))




  
 ggplot(data = st_as_sf(df3) %>% mutate(vacuna = vacuna*100,
                                       vacuna_cut = cut_interval(vacuna, n = 5))) +

  geom_sf(aes(fill = vacuna_cut)) +

  viridis::scale_fill_viridis(discrete=T,option = "A", direction = 1)  +


  facet_wrap(facets = ~vacunatipo+ANIO, ncol = 11)
  



ggsave("gg.png",width = 15,height = 15)
  
  

```

# PROPORCION POR CRED

```{r, echo=F, warning=F, message=F, error=F}
df3<-df2 %>% 
  
  mutate(
    ptv = map(.x = df , 
                 .f = ~svyby(~MOV_PTV_e1, by=~CRED, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV_COMPLETA") %>% 
                select(-`se.as.numeric(MOV_PTV_e1)`,-MOV_PTV_e1) %>% data.frame),
    
    neumo = map(.x = df , 
                 .f = ~svyby(~MOV_NEUMO_e1, by=~CRED, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                  
                  mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO_COMPLETA") %>% 
                  select(-`se.as.numeric(MOV_NEUMO_e1)`,-MOV_NEUMO_e1) %>% data.frame),
    
    influ = map(.x = df , 
                 .f = ~svyby(~MOV_INFLU_e1, by=~CRED, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                  
                  mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU_COMPLETA") %>%
                  select(-`se.as.numeric(MOV_INFLU_e1)`,-MOV_INFLU_e1) %>% data.frame),
    
    rota = map(.x = df , 
                 .f = ~svyby(~MOV_ROTA_e1, by=~CRED, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                 
                 mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA_COMPLETA") %>%
                 select(-`se.as.numeric(MOV_ROTA_e1)`,-MOV_ROTA_e1) %>% data.frame) ) %>%
  
  select(-data) %>% 
  
  mutate(
  
  pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
  pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
  
  total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
  
) %>% 
  
  select(ANIO,total) %>% 
  
  ungroup() %>% 
  
  unnest(cols = c(total)) %>% 
  
  #full_join(region_shape, by="DEPARTAMEN") %>% 
  
  mutate(ANIO = as.character(ANIO))



ggplot(data = df3, aes(x = vacunatipo, y = vacuna, fill = CRED)) +
  
  geom_col( position = position_dodge(width = 1), width = 0.8) +
  
  geom_errorbar(aes(ymin = ci_l, 
                    ymax = ci_u), 
                
                position = position_dodge(width = 1), 
                
                width = 0.25) +
  
  
  scale_fill_brewer(palette = 9) +
  
  facet_wrap(facets = ~ANIO, ncol = 5) + 
  
  theme_bw() +
  
  theme(axis.text.x = element_text(angle = 270))
```

# PROPORCION POR LUGAR DONDE TIENE CRED

```{r, echo=F, warning=F, message=F, error=F}
df3<-df2 %>% 
  
  mutate(
    ptv = map(.x = df , 
                 .f = ~svyby(~MOV_PTV_e1, by=~CREDLUGAR, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV_COMPLETA") %>% 
                select(-`se.as.numeric(MOV_PTV_e1)`,-MOV_PTV_e1) %>% data.frame),
    
    neumo = map(.x = df , 
                 .f = ~svyby(~MOV_NEUMO_e1, by=~CREDLUGAR, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                  
                  mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO_COMPLETA") %>% 
                  select(-`se.as.numeric(MOV_NEUMO_e1)`,-MOV_NEUMO_e1) %>% data.frame),
    
    influ = map(.x = df , 
                 .f = ~svyby(~MOV_INFLU_e1, by=~CREDLUGAR, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                  
                  mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU_COMPLETA") %>%
                  select(-`se.as.numeric(MOV_INFLU_e1)`,-MOV_INFLU_e1) %>% data.frame),
    
    rota = map(.x = df , 
                 .f = ~svyby(~MOV_ROTA_e1, by=~CREDLUGAR, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                 
                 mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA_COMPLETA") %>%
                 select(-`se.as.numeric(MOV_ROTA_e1)`,-MOV_ROTA_e1) %>% data.frame) ) %>%
  
  select(-data) %>% 
  
  mutate(
  
  pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
  pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
  
  total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
  
) %>% 
  
  select(ANIO,total) %>% 
  
  ungroup() %>% 
  
  unnest(cols = c(total)) %>% 
  
  #full_join(region_shape, by="DEPARTAMEN") %>% 
  
  mutate(ANIO = as.character(ANIO))


ggplot(data = df3, aes(x = vacunatipo, y = vacuna, fill = CREDLUGAR)) +
  
  geom_col( position = position_dodge(width = 1), width = 0.8) +
  
  geom_errorbar(aes(ymin = ci_l, 
                    ymax = ci_u), 
                
                position = position_dodge(width = 1), 
                
                width = 0.25) +
  
  
  scale_fill_brewer(palette = 9) +
  
  facet_wrap(facets = ~ANIO, ncol = 11) + 
  
  theme_bw() +
  
  theme(axis.text.x = element_text(angle = 270))

```

# TIPO DE RESIDENCIA

```{r, echo=F, warning=F, message=F, error=F}
df3<-df2 %>% 
  
  mutate(
    ptv = map(.x = df , 
                 .f = ~svyby(~MOV_PTV_e1, by=~TIPORESIDENCIA+DEPARTAMEN, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV_COMPLETA") %>% 
                select(-`se.as.numeric(MOV_PTV_e1)`,-MOV_PTV_e1) %>% data.frame),
    
    neumo = map(.x = df , 
                 .f = ~svyby(~MOV_NEUMO_e1, by=~TIPORESIDENCIA+DEPARTAMEN, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                  
                  mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO_COMPLETA") %>% 
                  select(-`se.as.numeric(MOV_NEUMO_e1)`,-MOV_NEUMO_e1) %>% data.frame),
    
    influ = map(.x = df , 
                 .f = ~svyby(~MOV_INFLU_e1, by=~TIPORESIDENCIA+DEPARTAMEN, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                  
                  mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU_COMPLETA") %>%
                  select(-`se.as.numeric(MOV_INFLU_e1)`,-MOV_INFLU_e1) %>% data.frame),
    
    rota = map(.x = df , 
                 .f = ~svyby(~MOV_ROTA_e1, by=~TIPORESIDENCIA+DEPARTAMEN, design =.x, FUN=svyciprop, vartype=c('se','ci')) %>%
                 
                 mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA_COMPLETA") %>%
                 select(-`se.as.numeric(MOV_ROTA_e1)`,-MOV_ROTA_e1) %>% data.frame) ) %>%
  
  select(-data) %>% 
  
  mutate(
  
  pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
  pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
  
  total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
  
) %>% 
  
  select(ANIO,total) %>% 
  
  ungroup() %>% 
  
  unnest(cols = c(total)) %>% 
  
  full_join(region_shape, by="DEPARTAMEN") %>% 
  
  mutate(ANIO = as.character(ANIO))




ggplot(data = st_as_sf(df3) %>% mutate(vacuna = vacuna*100,
                                       vacuna_cut = cut_interval(vacuna, n = 6))) +
  
  geom_sf(aes(fill = vacuna_cut)) +
  
  viridis::scale_fill_viridis(option = "D", direction = 1, discrete = T)  + 
  
  
  facet_wrap(facets = ~TIPORESIDENCIA+ANIO) +
  
  theme_bw()

```

# EDUCACION DE LA MADRE

```{r, echo=F, warning=F, message=F, error=F}
PTV<-svyby(~MOV_PTV_e1_2, by=~EDU_MADRE, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_PTV_e1_2)`,-MOV_PTV_e1_2)


NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~EDU_MADRE, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_NEUMO_e1_2)`,-MOV_NEUMO_e1_2)


INFLU<-svyby(~MOV_INFLU_e1_2, by=~EDU_MADRE, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_INFLU_e1_2)`,-MOV_INFLU_e1_2) 


ROTA<-svyby(~MOV_ROTA_e1, by=~EDU_MADRE, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_ROTA_e1)`,-MOV_ROTA_e1)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA) 



ggplot(data = df2, aes(x = vacunatipo, y = vacuna, fill = EDU_MADRE)) +
  
  geom_col( position = position_dodge(width = 1), width = 0.8) +
  
  geom_errorbar(aes(ymin = ci_l, 
                    ymax = ci_u), 
                
                position = position_dodge(width = 1), 
                
                width = 0.25) +
  
  
  scale_fill_brewer(palette = 9) +
  
  theme_bw()


```

# INDICE DE RIQUEZA

```{r, echo=F, warning=F, message=F, error=F, fig.width= 15, fig.height= 15}
PTV<-svyby(~MOV_PTV_e1_2, by=~INDICERIQUEZA + DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_PTV_e1_2)`,-MOV_PTV_e1_2)


NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~INDICERIQUEZA +DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_NEUMO_e1_2)`,-MOV_NEUMO_e1_2)


INFLU<-svyby(~MOV_INFLU_e1_2, by=~INDICERIQUEZA +DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_INFLU_e1_2)`,-MOV_INFLU_e1_2) 


ROTA<-svyby(~MOV_ROTA_e1, by=~INDICERIQUEZA +DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_ROTA_e1)`,-MOV_ROTA_e1)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA) %>% full_join(region_shape, by = c("DEPARTAMEN"))



# ggplot(data = df2, aes(x = vacunatipo, y = vacuna, fill = INDICERIQUEZA)) +
#   
#   geom_col( position = position_dodge(width = 1), width = 0.8) +
#   
#   geom_errorbar(aes(ymin = ci_l, 
#                     ymax = ci_u), 
#                 
#                 position = position_dodge(width = 1), 
#                 
#                 width = 0.25) +
#   
#   
#   scale_fill_brewer(palette = 9) +
#   
#   theme_bw()



ggplot(data = st_as_sf(df2) %>% mutate(vacuna = vacuna*100,
                                       vacuna_cut = cut_interval(vacuna, n = 6))) +
  
  geom_sf(aes(fill = vacuna_cut)) +
  
  viridis::scale_fill_viridis(option = "D", direction = 1, discrete = T)  + 
  
  
  facet_wrap(facets = ~INDICERIQUEZA + vacunatipo, nrow = 5) +
  
  theme_bw()


```

# ETINIA MADRE

```{r, echo=F, warning=F, message=F, error=F}
PTV<-svyby(~MOV_PTV_e1_2, by=~ETNIA_MADRE, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_PTV_e1_2)`,-MOV_PTV_e1_2)


NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~ETNIA_MADRE, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_NEUMO_e1_2)`,-MOV_NEUMO_e1_2)


INFLU<-svyby(~MOV_INFLU_e1_2, by=~ETNIA_MADRE, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_INFLU_e1_2)`,-MOV_INFLU_e1_2) 


ROTA<-svyby(~MOV_ROTA_e1, by=~ETNIA_MADRE, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_ROTA_e1)`,-MOV_ROTA_e1)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA) 

mycolors <- colorRampPalette(brewer.pal(1, "Set2"))(12)

ggplot(data = df2, aes(x = vacunatipo, y = vacuna, fill = as.factor(ETNIA_MADRE))) +
  
  geom_col( position = position_dodge(width = 1), width = 0.8) +
  
  geom_errorbar(aes(ymin = ci_l, 
                    ymax = ci_u), 
                
                position = position_dodge(width = 1), 
                
                width = 0.25) +
  
  
  scale_fill_manual(values = mycolors) + 
  
  theme_bw() +
  
  
  coord_flip()

```

# EDUCACION MADRE

```{r, echo=F, warning=F, message=F, error=F, fig.width= 15, fig.height= 15}
PTV<-svyby(~MOV_PTV_e1_2, by=~EDU_MADRE + DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_PTV_e1_2)`,-MOV_PTV_e1_2)


NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~EDU_MADRE +DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_NEUMO_e1_2)`,-MOV_NEUMO_e1_2)


INFLU<-svyby(~MOV_INFLU_e1_2, by=~EDU_MADRE +DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_INFLU_e1_2)`,-MOV_INFLU_e1_2) 


ROTA<-svyby(~MOV_ROTA_e1, by=~EDU_MADRE +DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_ROTA_e1)`,-MOV_ROTA_e1)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA) %>% full_join(region_shape, by = c("DEPARTAMEN"))



# ggplot(data = df2, aes(x = vacunatipo, y = vacuna, fill = as.factor(EDU_MADRE))) +
#   
#   geom_col( position = position_dodge(width = 1), width = 0.8) +
#   
#   geom_errorbar(aes(ymin = ci_l, 
#                     ymax = ci_u), 
#                 
#                 position = position_dodge(width = 1), 
#                 
#                 width = 0.25) +
#   
#   
#   scale_fill_brewer(palette = 9) +
#   
#   theme_bw()


ggplot(data = st_as_sf(df2) %>% mutate(vacuna = vacuna*100,
                                       vacuna_cut = cut_interval(vacuna, n = 6))) +
  
  geom_sf(aes(fill = vacuna_cut)) +
  
  viridis::scale_fill_viridis(option = "D", direction = 1, discrete = T)  + 
  
  
  facet_wrap(facets = ~EDU_MADRE + vacunatipo, nrow = 2) +
  
  theme_bw()


#MOV2020_2 %>% filter(DEPARTAMEN == "PUNO" & MOV_ROTA_e1 == 1 & EDU_MADRE == "sin educ")

```

# EDAD MADRE

```{r, echo=F, warning=F, message=F, error=F, fig.width= 10, fig.height= 10}
PTV<-svyby(~MOV_PTV_e1_2, by=~EDAD_MADRE + DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_PTV_e1_2)`,-MOV_PTV_e1_2)


NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~EDAD_MADRE +DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_NEUMO_e1_2)`,-MOV_NEUMO_e1_2)


INFLU<-svyby(~MOV_INFLU_e1_2, by=~EDAD_MADRE +DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_INFLU_e1_2)`,-MOV_INFLU_e1_2) 


ROTA<-svyby(~MOV_ROTA_e1, by=~EDAD_MADRE +DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA_COMPLETA") %>% 
  
  select(-`se.as.numeric(MOV_ROTA_e1)`,-MOV_ROTA_e1)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA) %>% full_join(region_shape, by = c("DEPARTAMEN"))


ggplot(data = st_as_sf(df2) %>% mutate(vacuna = vacuna*100,
                                       vacuna_cut = cut_interval(vacuna, n = 6))) +
  
  geom_sf(aes(fill = vacuna_cut)) +
  
  viridis::scale_fill_viridis(option = "D", direction = 1, discrete = T)  + 
  
  
  facet_wrap(facets = ~EDAD_MADRE + vacunatipo, nrow = 2) +
  
  theme_bw()
```

# REGION / DOSIS 1 Y 2 (TARJETA)

```{r}
PTV<-svyby(~S45PV1_1, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45PV1_1,vacunatipo = "PTV_1") %>% 
  
  select(-`se.as.numeric(S45PV1_1)`,-S45PV1_1)

PTV2<-svyby(~S45PV2_1, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45PV2_1,vacunatipo = "PTV_2") %>% 
  
  select(-`se.as.numeric(S45PV2_1)`,-S45PV2_1)

PTV3<-svyby(~S45PV3_1, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45PV3_1,vacunatipo = "PTV_3") %>% 
  
  select(-`se.as.numeric(S45PV3_1)`,-S45PV3_1)






NEUMO1<-svyby(~S45NM1_1, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45NM1_1,vacunatipo = "NEUMO_1") %>% 
  
  select(-`se.as.numeric(S45NM1_1)`,-S45NM1_1)

NEUMO2<-svyby(~S45NM2_1, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45NM2_1,vacunatipo = "NEUMO_2") %>% 
  
  select(-`se.as.numeric(S45NM2_1)`,-S45NM2_1)

NEUMO3<-svyby(~S45NM3_1, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45NM3_1,vacunatipo = "NEUMO_3") %>% 
  
  select(-`se.as.numeric(S45NM3_1)`,-S45NM3_1)






INFLU1<-svyby(~S45IF1_1, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45IF1_1,vacunatipo = "INFLU_1") %>% 
  
  select(-`se.as.numeric(S45IF1_1)`,-S45IF1_1)

INFLU2<-svyby(~S45IF2_1, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45IF2_1,vacunatipo = "INFLU_2") %>% 
  
  select(-`se.as.numeric(S45IF2_1)`,-S45IF2_1)




ROTA1<-svyby(~S45RT1_1, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45RT1_1,vacunatipo = "ROTA_1") %>% 
  
  select(-`se.as.numeric(S45RT1_1)`,-S45RT1_1)

ROTA2<-svyby(~S45RT2_1, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45RT2_1,vacunatipo = "ROTA_2") %>% 
  
  select(-`se.as.numeric(S45RT2_1)`,-S45RT2_1)

```

## Graficos con tarjeta

```{r}
ggplot() + 
  
  geom_col(data = PTV, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = PTV2, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = PTV3, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  coord_flip() +
  
   theme_minimal()


ggplot() + 
  
  geom_col(data = NEUMO1, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = NEUMO2, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = NEUMO3, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  coord_flip() +
  
  facet_wrap(~EDAD_CAT_V) +
  
   theme_minimal()


ggplot() + 
  
  geom_col(data = INFLU1, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = INFLU2, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  coord_flip() +
  
  facet_wrap(~EDAD_CAT_V) +
  
   theme_minimal()



ggplot() + 
  
  geom_col(data = ROTA1, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = ROTA2, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +

  
  coord_flip() +
  
  theme_minimal()
  

INFLU1 %>% 
  
  bind_rows(INFLU2) %>% 
 
  
  ggplot(aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo)) + 
  
  geom_col(position = "fill") +
  
  coord_flip() + facet_wrap(~EDAD_CAT_V)
```

# REGION / DOSIS 1 Y 2 (MADRE)

```{r}
PTV<-svyby(~S45PV1_2, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45PV1_2,vacunatipo = "PTV_1") %>% 
  
  select(-`se.as.numeric(S45PV1_2)`,-S45PV1_2)

PTV2<-svyby(~S45PV2_2, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45PV2_2,vacunatipo = "PTV_2") %>% 
  
  select(-`se.as.numeric(S45PV2_2)`,-S45PV2_2)

PTV3<-svyby(~S45PV3_2, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45PV3_2,vacunatipo = "PTV_3") %>% 
  
  select(-`se.as.numeric(S45PV3_2)`,-S45PV3_2)






NEUMO1<-svyby(~S45NM1_2, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45NM1_2,vacunatipo = "NEUMO_1") %>% 
  
  select(-`se.as.numeric(S45NM1_2)`,-S45NM1_2)

NEUMO2<-svyby(~S45NM2_2, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45NM2_2,vacunatipo = "NEUMO_2") %>% 
  
  select(-`se.as.numeric(S45NM2_2)`,-S45NM2_2)

NEUMO3<-svyby(~S45NM3_2, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45NM3_2,vacunatipo = "NEUMO_3") %>% 
  
  select(-`se.as.numeric(S45NM3_2)`,-S45NM3_2)






INFLU1<-svyby(~S45IF1_2, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45IF1_2,vacunatipo = "INFLU_1") %>% 
  
  select(-`se.as.numeric(S45IF1_2)`,-S45IF1_2)

INFLU2<-svyby(~S45IF2_2, by=~DEPARTAMEN+EDAD_CAT_V, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45IF2_2,vacunatipo = "INFLU_2") %>% 
  
  select(-`se.as.numeric(S45IF2_2)`,-S45IF2_2)




ROTA1<-svyby(~S45RT1_2, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45RT1_2,vacunatipo = "ROTA_1") %>% 
  
  select(-`se.as.numeric(S45RT1_2)`,-S45RT1_2)

ROTA2<-svyby(~S45RT2_2, by=~DEPARTAMEN, design =df, FUN=svyciprop, vartype=c('se','ci')) %>% 
  
  mutate(vacuna = S45RT2_2,vacunatipo = "ROTA_2") %>% 
  
  select(-`se.as.numeric(S45RT2_2)`,-S45RT2_2)
```

## Graficos (MADRE)

```{r}
ggplot() + 
  
  geom_col(data = PTV, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = PTV2, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = PTV3, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  coord_flip() +
  
   theme_minimal()


ggplot() + 
  
  geom_col(data = NEUMO1, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = NEUMO2, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = NEUMO3, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  coord_flip() +
  
  facet_wrap(~EDAD_CAT_V) +
  
   theme_minimal()


ggplot() + 
  
  geom_col(data = INFLU1, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = INFLU2, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  coord_flip() +
  
  facet_wrap(~EDAD_CAT_V) +
  
   theme_minimal()



ggplot() + 
  
  geom_col(data = ROTA1, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +
  
  geom_col(data = ROTA2, aes(x = DEPARTAMEN, y = vacuna, fill = vacunatipo), alpha = 0.5) +

  
  coord_flip() +
  
  theme_minimal()
  
  
```
