---
title: "Untitled"
output: html_document
---

```{r, warning=F, message=F,comment=F}

library(tidyverse)
library(survey)
library(jtools)
library(sandwich)
library(sf)

region_shape <- st_read("./ENDES/Regiones/DEPARTAMENTOS.shp")
```

```{r}
# Base de trabajo
MOV_GENERAL <- read.csv("./BD.INTERMEDIAS/mov_general.csv")

df2<-MOV_GENERAL %>% 
  
  #filter(!is.na(MOV_PTV_e1)) %>% 
  
  group_by(ANIO) %>% 
  nest() %>%
  mutate(
    df= map(.x = data, 
      .f = ~svydesign(id =~ V001, strata =~ V022, probs=~V005, data=.x))) 

options(survey.lonely.psu="remove")

```

# EVENTO

## EDUCACION DE LA MADRE

```{r}
df3<-
  df2 %>% 
  mutate(
    
    ptv = map(.x =df,
              .f = ~svyby(~MOV_PTV_e1, by=~EDU_MADRE, design =.x, FUN=svytotal, na.rm = T) %>% 
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV",
                       orden = case_when(EDU_MADRE == "sin educ" ~ 0,
                                         EDU_MADRE == "primaria" ~ 1,
                                         EDU_MADRE == "secundaria" ~ 2,
                                         EDU_MADRE == "superior" ~ 3)) %>% 
                
                select(-MOV_PTV_e1) %>% 
                
                left_join(
                  
                  svytotal(~EDU_MADRE, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("EDU_MADRE") %>%
                    
                    mutate(
                      EDU_MADRE = substring(EDU_MADRE,10))) %>%
                
                select(EDU_MADRE,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    
    neumo = map(.x =df,
                .f = ~svyby(~MOV_NEUMO_e1, by=~EDU_MADRE, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO",
                         orden = case_when(EDU_MADRE == "sin educ" ~ 0,
                                         EDU_MADRE == "primaria" ~ 1,
                                         EDU_MADRE == "secundaria" ~ 2,
                                         EDU_MADRE == "superior" ~ 3)) %>% 
                  
                  select(-MOV_NEUMO_e1) %>% 
                  
                  left_join(
                    
                    svytotal(~EDU_MADRE, design = .x, na.rm = T) %>%
                      
                      data.frame() %>%
                      
                      rownames_to_column("EDU_MADRE") %>%
                      
                      mutate(
                        EDU_MADRE = substring(EDU_MADRE,10))) %>%
                  
                  select(EDU_MADRE,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    influ = map(.x =df,
                .f = ~svyby(~MOV_INFLU_e1, by=~EDU_MADRE, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU",
                         orden = case_when(EDU_MADRE == "sin educ" ~ 0,
                                         EDU_MADRE == "primaria" ~ 1,
                                         EDU_MADRE == "secundaria" ~ 2,
                                         EDU_MADRE == "superior" ~ 3)) %>% 
                  
                  select(-MOV_INFLU_e1) %>% 
                  
                  left_join(
                    
                    svytotal(~EDU_MADRE, design = .x, na.rm = T) %>%
                      
                      data.frame() %>%
                      
                      rownames_to_column("EDU_MADRE") %>%
                      
                      mutate(
                        EDU_MADRE = substring(EDU_MADRE,10))) %>%
                  
                  select(EDU_MADRE,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    rota  = map(.x =df,
                .f = ~svyby(~MOV_ROTA_e1, by=~EDU_MADRE, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA",
                         orden = case_when(EDU_MADRE == "sin educ" ~ 0,
                                         EDU_MADRE == "primaria" ~ 1,
                                         EDU_MADRE == "secundaria" ~ 2,
                                         EDU_MADRE == "superior" ~ 3)) %>% 
                  
                  select(-MOV_ROTA_e1) %>% 
                  
                  left_join(
                    
                    svytotal(~EDU_MADRE, design =.x, na.rm = T) %>%
                      
                      data.frame() %>%
                      
                      rownames_to_column("EDU_MADRE") %>%
                      
                      mutate(
                        EDU_MADRE = substring(EDU_MADRE,10))) %>%
                  
                  select(EDU_MADRE,orden,total,vacuna,vacunatipo,se,-`SE`))) %>% 
  
  
  mutate(
    
    pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
    pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
    
    total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
    
    hr = map(.x = total,
             .f = ~h_prop(.x)),
    
    ssirii = map(.x = total,
                 .f = ~sii_rii(.x)),
    
    
    graf = map(.x = hr,
               .f = ~gg(.x))
    
  ) 


# SII y RII por año (2010 - 2020)

  df3 %>% select(ANIO,ssirii) %>% 
  unnest(cols = c(ssirii)) %>% 
  as.data.frame() %>% 
  ungroup() %>% 
    
  
  pivot_longer(cols = c(rii,ssi), names_to = "index") %>% 
  
  ggplot() +
  geom_line(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
  geom_point(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
    
  scale_color_manual(values = c("#346751","#C84B31","#FFCC29","blue4")) +
  facet_wrap(~index, scales = "free", labeller = labeller(index = c("rii" = "RII",
                                                                    "ssi" = "SII"))) +
    xlab("Years")+
    ylab("Value")+
    #theme_minimal()+
    theme(
    axis.title = element_text(face ="bold", size = 11),
    legend.text = element_text(size = 8, face = "bold"),
    axis.text = element_text(face = "bold"),
    axis.text.x = element_text( size = 11),
    legend.position = "top",
    legend.title = element_blank(),
    axis.line = element_line(colour = "black", size = 1),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold")
  )
  
  ggsave("SII_RII_education.png",width = 18, height = 5)

# Grafico: tasa vs HR
ggsave("rr.png",cowplot::plot_grid(plotlist = df3$graf), width = 18, height = 15)

#########


temp<-df3 %>% 
  select(ANIO,hr) %>% 
  unnest(cols = c(hr)) %>% 
  as.data.frame() %>% 
  group_by(as.factor(ANIO)) %>% 
  nest() %>% 
  mutate(grafico = map(.x = data,
                       .f = ~ggplot(data = .x, aes(x = EDU_MADRE, y = tasa, fill = as.factor(ANIO), group = as.factor(ANIO)))+
  geom_col(fill = "#AA5674")+
  geom_point()+
  geom_smooth(method = "lm",se = F)+
    xlab("Maternal education") +
    ylab("Rate")+
    scale_x_discrete(labels = c("NE","PS","HS","SE"))+
    theme(
    axis.title = element_text(face ="bold", size = 8),
    legend.text = element_text(size = 9, face = "bold"),
    axis.text = element_text(face = "bold"),
    axis.text.x = element_text( size = 8),
    legend.position = "top",
    legend.title = element_blank(),
    axis.line = element_line(colour = "black", size = 1),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", size = 8)) +
  facet_wrap(~vacunatipo, scales = "free")))


cowplot::plot_grid(plotlist = temp$grafico)

ggsave("cols_slope_education.png", width = 13, height = 9)


temp$data[[1]]

```


## INDICE RIQUEZA

```{r}
df3<-
  df2 %>% 
  mutate(
    
    ptv = map(.x =df,
              .f = ~svyby(~MOV_PTV_e1, by=~INDICERIQUEZA, design =.x, FUN=svytotal, na.rm = T) %>% 
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV",
                       orden =as.numeric(as.factor(INDICERIQUEZA))) %>% 
                
                select(-MOV_PTV_e1) %>% 
                
                left_join(
                  
                  svytotal(~INDICERIQUEZA, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("INDICERIQUEZA") %>%
                    
                    mutate(
                      INDICERIQUEZA = substring(INDICERIQUEZA,14))) %>%
                
                select(INDICERIQUEZA,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    
    neumo = map(.x =df,
                .f = ~svyby(~MOV_NEUMO_e1, by=~INDICERIQUEZA, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO",
                         orden =as.numeric(as.factor(INDICERIQUEZA))) %>% 
                  
                  select(-MOV_NEUMO_e1) %>% 
                  
                  left_join(
                  
                  svytotal(~INDICERIQUEZA, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("INDICERIQUEZA") %>%
                    
                    mutate(
                      INDICERIQUEZA = substring(INDICERIQUEZA,14))) %>%
                
                select(INDICERIQUEZA,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    influ = map(.x =df,
                .f = ~svyby(~MOV_INFLU_e1, by=~INDICERIQUEZA, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU",
                         orden =as.numeric(as.factor(INDICERIQUEZA))) %>% 
                  
                  select(-MOV_INFLU_e1) %>% 
                  
                  left_join(
                  
                  svytotal(~INDICERIQUEZA, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("INDICERIQUEZA") %>%
                    
                    mutate(
                      INDICERIQUEZA = substring(INDICERIQUEZA,14))) %>%
                
                select(INDICERIQUEZA,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    rota  = map(.x =df,
                .f = ~svyby(~MOV_ROTA_e1, by=~INDICERIQUEZA, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA",
                         orden =as.numeric(as.factor(INDICERIQUEZA))) %>% 
                  
                  select(-MOV_ROTA_e1) %>% 
                  
                  left_join(
                  
                  svytotal(~INDICERIQUEZA, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("INDICERIQUEZA") %>%
                    
                    mutate(
                      INDICERIQUEZA = substring(INDICERIQUEZA,14))) %>%
                
                select(INDICERIQUEZA,orden,total,vacuna,vacunatipo,se,-`SE`))) %>% 
  
  
  mutate(
    
    pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
    pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
    
    total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
    
    hr = map(.x = total,
             .f = ~h_prop(.x)),
    
    ssirii = map(.x = total,
                 .f = ~sii_rii(.x)),
    
    
    graf = map(.x = hr,
               .f = ~gg(.x))
    
  ) 


# SII y RII por año (2010 - 2020)

df3 %>% select(ANIO,ssirii) %>% 
  unnest(cols = c(ssirii)) %>% 
  as.data.frame() %>% 
  ungroup() %>% 
  mutate(
    rii.pct = (rii-1)*100
  ) %>% 
  
  pivot_longer(cols = c(rii,ssi), names_to = "index") %>% 
  
  ggplot() +
  geom_line(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
  geom_point(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
  scale_color_manual(values = c("#346751","#C84B31","#FFCC29","blue4")) +
  facet_wrap(~index, scales = "free", labeller = labeller(index = c("rii" = "RII",
                                                                    "ssi" = "SII"))) +
    xlab("Years")+
    ylab("Value")+
    #theme_minimal()+
    theme(
    axis.title = element_text(face ="bold", size = 11),
    legend.text = element_text(size = 8, face = "bold"),
    axis.text = element_text(face = "bold"),
    axis.text.x = element_text( size = 11),
    legend.position = "top",
    legend.title = element_blank(),
    axis.line = element_line(colour = "black", size = 1),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold")
  )

ggsave("SII_RII_RIQ.png",width = 15)

#######

temp<-df3 %>% 
  select(ANIO,hr) %>% 
  unnest(cols = c(hr)) %>% 
  as.data.frame() %>% 
  group_by(as.factor(ANIO)) %>% 
  nest() %>% 
  mutate(grafico = map(.x = data,
                       .f = ~ggplot(data = .x, aes(x = INDICERIQUEZA, y = tasa, fill = as.factor(ANIO), group = as.factor(ANIO)))+
  geom_col(fill = "#AA5674")+
  geom_point()+
  geom_smooth(method = "lm",se = F)+
    xlab("Poverty decile") +
    ylab("Rate")+
    scale_x_discrete(labels = c("1st","2nd","3rd","4th","5th"))+
    theme(
    axis.title = element_text(face ="bold", size = 8),
    legend.text = element_text(size = 9, face = "bold"),
    axis.text = element_text(face = "bold"),
    axis.text.x = element_text( size = 8),
    legend.position = "top",
    legend.title = element_blank(),
    axis.line = element_line(colour = "black", size = 1),
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", size = 8)) +
  facet_wrap(~vacunatipo, scales = "free")))


cowplot::plot_grid(plotlist = temp$grafico)

ggsave("cols_slope_RIQ.png", width = 13, height = 9)





```






# EVENTO POR REGION


```{r}
df3<-
  df2 %>% 
  mutate(
    
    ptv = map(.x =df,
              .f = ~svyby(~MOV_PTV_e1, by=~INDICERIQUEZA+DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV",
                       orden =as.numeric(as.factor(INDICERIQUEZA))) %>% 
                
                select(-MOV_PTV_e1) %>% 
                
                left_join(
                  
                  svytotal(~INDICERIQUEZA, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("INDICERIQUEZA") %>%
                    
                    mutate(
                      INDICERIQUEZA = substring(INDICERIQUEZA,14))) %>%
                
                select(DEPARTAMEN,INDICERIQUEZA,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    neumo = map(.x =df,
               .f = ~svyby(~MOV_NEUMO_e1, by=~INDICERIQUEZA+DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                 
                 mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO",
                        orden =as.numeric(as.factor(INDICERIQUEZA))) %>% 
                 
                 select(-MOV_NEUMO_e1) %>% 
                 
                 left_join(
                   
                   svytotal(~INDICERIQUEZA, design = .x, na.rm = T) %>%
                     
                     data.frame() %>%
                     
                     rownames_to_column("INDICERIQUEZA") %>%
                     
                     mutate(
                       INDICERIQUEZA = substring(INDICERIQUEZA,14))) %>%
                 
                 select(DEPARTAMEN,INDICERIQUEZA,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    
    rota = map(.x =df,
               .f = ~svyby(~MOV_ROTA_e1, by=~INDICERIQUEZA+DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                 
                 mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA",
                        orden =as.numeric(as.factor(INDICERIQUEZA))) %>% 
                 
                 select(-MOV_ROTA_e1) %>% 
                 
                 left_join(
                   
                   svytotal(~INDICERIQUEZA, design = .x, na.rm = T) %>%
                     
                     data.frame() %>%
                     
                     rownames_to_column("INDICERIQUEZA") %>%
                     
                     mutate(
                       INDICERIQUEZA = substring(INDICERIQUEZA,14))) %>%
                 
                 select(DEPARTAMEN,INDICERIQUEZA,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    influ = map(.x =df,
              .f = ~svyby(~MOV_INFLU_e1, by=~INDICERIQUEZA+DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                
                mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU",
                       orden =as.numeric(as.factor(INDICERIQUEZA))) %>% 
                
                select(-MOV_INFLU_e1) %>% 
                
                left_join(
                  
                  svytotal(~INDICERIQUEZA, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("INDICERIQUEZA") %>%
                    
                    mutate(
                      INDICERIQUEZA = substring(INDICERIQUEZA,14))) %>%
                
                select(DEPARTAMEN,INDICERIQUEZA,total,orden,vacuna,vacunatipo,se,-`SE`))
    
  ) %>% 
  
  
  mutate(
    pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
    pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
    
    total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
    
    hr = map(.x = total,
             .f = ~h_prop.map(.x)),
    
    ssirii = map(.x = total,
                 .f = ~sii_rii_map(.x))
    
  )

df4<-df3 %>% 
  select(ANIO,ssirii) %>% 
  unnest(cols = c(ssirii)) %>%
  #filter(vacunatipo%in%c("INFLU")) %>% 
  
  left_join(region_shape, by = "DEPARTAMEN") %>% 
  
  group_by(vacunatipo) %>% 
  
  st_as_sf %>%
  
  nest() %>% 
  
  mutate(
    
    grafico = map(.x = data,
                  .f = ~gg2(.x))
  )
  


cowplot::plot_grid(plotlist = df4$grafico, labels = c("A","B","C","D"))
ggsave("SII_RIQ_REGION.png",width = 19,height = 8)


```


```{r}
df3<-
  df2 %>% 
  mutate(
    
    ptv = map(.x =df,
              .f = ~svyby(~MOV_PTV_e1, by=~EDU_MADRE+DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV",
                       orden =as.numeric(as.factor(EDU_MADRE))) %>% 
                
                select(-MOV_PTV_e1) %>% 
                
                left_join(
                  
                  svytotal(~EDU_MADRE, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("EDU_MADRE") %>%
                    
                    mutate(
                      EDU_MADRE = substring(EDU_MADRE,10))) %>%
                
                select(DEPARTAMEN,EDU_MADRE,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    neumo = map(.x =df,
               .f = ~svyby(~MOV_NEUMO_e1, by=~EDU_MADRE+DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                 
                 mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO",
                        orden =as.numeric(as.factor(EDU_MADRE))) %>% 
                 
                 select(-MOV_NEUMO_e1) %>% 
                 
                 left_join(
                   
                   svytotal(~EDU_MADRE, design = .x, na.rm = T) %>%
                     
                     data.frame() %>%
                     
                     rownames_to_column("EDU_MADRE") %>%
                     
                     mutate(
                       EDU_MADRE = substring(EDU_MADRE,10))) %>%
                 
                 select(DEPARTAMEN,EDU_MADRE,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    
    rota = map(.x =df,
               .f = ~svyby(~MOV_ROTA_e1, by=~EDU_MADRE+DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                 
                 mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA",
                        orden =as.numeric(as.factor(EDU_MADRE))) %>% 
                 
                 select(-MOV_ROTA_e1) %>% 
                 
                 left_join(
                   
                   svytotal(~EDU_MADRE, design = .x, na.rm = T) %>%
                     
                     data.frame() %>%
                     
                     rownames_to_column("EDU_MADRE") %>%
                     
                     mutate(
                       EDU_MADRE = substring(EDU_MADRE,10))) %>%
                 
                 select(DEPARTAMEN,EDU_MADRE,orden,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    influ = map(.x =df,
              .f = ~svyby(~MOV_INFLU_e1, by=~EDU_MADRE+DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                
                mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU",
                       orden =as.numeric(as.factor(EDU_MADRE))) %>% 
                
                select(-MOV_INFLU_e1) %>% 
                
                left_join(
                  
                  svytotal(~EDU_MADRE, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("EDU_MADRE") %>%
                    
                    mutate(
                      EDU_MADRE = substring(EDU_MADRE,10))) %>%
                
                select(DEPARTAMEN,EDU_MADRE,total,orden,vacuna,vacunatipo,se,-`SE`))
    
  ) %>% 
  
  
  mutate(
    pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
    pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
    
    total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
    
    hr = map(.x = total,
             .f = ~h_prop.map(.x)),
    
    ssirii = map(.x = total,
                 .f = ~sii_rii_map(.x))
    
  )


df4<-df3 %>% 
  select(ANIO,ssirii) %>% 
  unnest(cols = c(ssirii)) %>%
  #filter(vacunatipo%in%c("INFLU")) %>% 
  
  left_join(region_shape, by = "DEPARTAMEN") %>% 
  
  group_by(vacunatipo) %>% 
  
  st_as_sf %>%
  
  nest() %>% 
  
  mutate(
    
    grafico = map(.x = data,
                  .f = ~gg2(.x))
  )
  

cowplot::plot_grid(plotlist = df4$grafico, labels = c("A","B","C","D"))
ggsave("SSI_EDUC_REGION.png",width = 18,height = 10)

```


# OTROS

## DEPARTAMENTOS

```{r}
df3<-
  df2 %>% 
  mutate(
    
    ptv = map(.x =df,
              .f = ~svyby(~MOV_PTV_e1, by=~DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV",
                       orden =as.numeric(as.factor(DEPARTAMEN))) %>% 
                
                select(-MOV_PTV_e1) %>% 
                
                left_join(
                  
                  svytotal(~DEPARTAMEN, design = .x) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("DEPARTAMEN") %>%
                    
                    mutate(
                      DEPARTAMEN = substring(DEPARTAMEN,11))) %>%
                
                select(DEPARTAMEN,total,vacuna,vacunatipo,se,orden,-`SE`)),
    
    
    
    neumo = map(.x =df,
                .f = ~svyby(~MOV_NEUMO_e1, by=~DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO",
                         orden =as.numeric(as.factor(DEPARTAMEN))) %>% 
                  
                  select(-MOV_NEUMO_e1) %>% 
                  
                  left_join(
                    
                    svytotal(~DEPARTAMEN, design = .x) %>%
                      
                      data.frame() %>%
                      
                      rownames_to_column("DEPARTAMEN") %>%
                      
                      mutate(
                        DEPARTAMEN = substring(DEPARTAMEN,11))) %>%
                  
                  select(DEPARTAMEN,total,vacuna,vacunatipo,se,orden,-`SE`)),
    
    
    influ = map(.x =df,
                .f = ~svyby(~MOV_INFLU_e1, by=~DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU",
                         orden =as.numeric(as.factor(DEPARTAMEN))) %>% 
                  
                  select(-MOV_INFLU_e1) %>% 
                  
                  left_join(
                    
                    svytotal(~DEPARTAMEN, design = .x) %>%
                      
                      data.frame() %>%
                      
                      rownames_to_column("DEPARTAMEN") %>%
                      
                      mutate(
                        DEPARTAMEN = substring(DEPARTAMEN,11))) %>%
                  
                  select(DEPARTAMEN,total,vacuna,vacunatipo,se,orden,-`SE`)),
    
    
    rota  = map(.x =df,
                .f = ~svyby(~MOV_ROTA_e1, by=~DEPARTAMEN, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA",
                         orden =as.numeric(as.factor(DEPARTAMEN))) %>% 
                  
                  select(-MOV_ROTA_e1) %>% 
                  
                  left_join(
                    
                    svytotal(~DEPARTAMEN, design = .x) %>%
                      
                      data.frame() %>%
                      
                      rownames_to_column("DEPARTAMEN") %>%
                      
                      mutate(
                        DEPARTAMEN = substring(DEPARTAMEN,11))) %>%
                  
                  select(DEPARTAMEN,total,vacuna,vacunatipo,se,orden,-`SE`))) %>% 
  
  
  mutate(
    
    pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
    pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
    
    total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
    
     hr = map(.x = total,
              .f = ~h_prop(.x)),


     ssirii = map(.x = total,
                  .f = ~sii_rii(.x)),
    

     graf = map(.x = hr,
                .f = ~gg(.x))
    
  ) 

# SII y RII por año (2010 - 2020)

df3 %>% select(ANIO,ssirii) %>% 
  unnest(cols = c(ssirii)) %>% 
  as.data.frame() %>% 
  ungroup() %>% 
  pivot_longer(cols = c(ssi,rii), names_to = "index") %>% 
  
  ggplot() +
  geom_line(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
  geom_point(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
  
  facet_wrap(~index)

  
# Grafico: tasa vs HR
ggsave("tt.png",cowplot::plot_grid(plotlist = df3$graf), width = 18, height = 15)



df3$hr[[1]]
 
  
  
```



## CRED LUGAR

```{r}
df3<-
  df2 %>% 
  mutate(
    
    ptv = map(.x =df,
              .f = ~svyby(~MOV_PTV_e1, by=~CREDLUGAR, design =.x, FUN=svytotal, na.rm = T) %>% 
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV") %>% 
                
                select(-MOV_PTV_e1) %>% 
                
                left_join(
                  
                  svytotal(~CREDLUGAR, design = .x) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("CREDLUGAR") %>%
                    
                    mutate(
                      CREDLUGAR = substring(CREDLUGAR,10))) %>%
                
                select(CREDLUGAR,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    
    neumo = map(.x =df,
                .f = ~svyby(~MOV_NEUMO_e1, by=~CREDLUGAR, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO") %>% 
                  
                  select(-MOV_NEUMO_e1) %>% 
                  
                  left_join(
                    
                    svytotal(~CREDLUGAR, design = .x) %>%
                      
                      data.frame() %>%
                      
                      rownames_to_column("CREDLUGAR") %>%
                      
                      mutate(
                        CREDLUGAR = substring(CREDLUGAR,10))) %>%
                  
                  select(CREDLUGAR,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    influ = map(.x =df,
                .f = ~svyby(~MOV_INFLU_e1, by=~CREDLUGAR, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU") %>% 
                  
                  select(-MOV_INFLU_e1) %>% 
                  
                  left_join(
                    
                    svytotal(~CREDLUGAR, design = .x) %>%
                      
                      data.frame() %>%
                      
                      rownames_to_column("CREDLUGAR") %>%
                      
                      mutate(
                        CREDLUGAR = substring(CREDLUGAR,10))) %>%
                  
                  select(CREDLUGAR,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    rota  = map(.x =df,
                .f = ~svyby(~MOV_ROTA_e1, by=~CREDLUGAR, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA") %>% 
                  
                  select(-MOV_ROTA_e1) %>% 
                  
                  left_join(
                    
                    svytotal(~CREDLUGAR, design = .x) %>%
                      
                      data.frame() %>%
                      
                      rownames_to_column("CREDLUGAR") %>%
                      
                      mutate(
                        CREDLUGAR = substring(CREDLUGAR,10))) %>%
                  
                  select(CREDLUGAR,total,vacuna,vacunatipo,se,-`SE`))) %>% 
  
  
  mutate(
    
    pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
    pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
    
    total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
    
    hr = map(.x = total,
             .f = ~h_prop(.x)),
    
    ssirii = map(.x = total,
                 .f = ~sii_rii(.x)),
    
    
    graf = map(.x = hr,
               .f = ~gg(.x))
    
  ) 

# SII y RII por año (2010 - 2020)

  df3 %>% select(ANIO,ssirii) %>% 
  unnest(cols = c(ssirii)) %>% 
  as.data.frame() %>% 
  ungroup() %>% 
  pivot_longer(cols = c(ssi,rii), names_to = "index") %>% 
  
  ggplot() +
  geom_line(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
  geom_point(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
  
  facet_wrap(~index)

# Grafico: tasa vs HR
ggsave("qq.png",cowplot::plot_grid(plotlist = df3$graf), width = 18, height = 15)


  
```


## EDAD MADRE

```{r}
df3<-
  df2 %>% 
  mutate(
    
    ptv = map(.x =df,
              .f = ~svyby(~MOV_PTV_e1, by=~EDAD_MADRE, design =.x, FUN=svytotal, na.rm = T) %>% 
                
                mutate(vacuna = MOV_PTV_e1,vacunatipo = "PTV") %>% 
                
                select(-MOV_PTV_e1) %>% 
                
                left_join(
                  
                  svytotal(~EDAD_MADRE, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("EDAD_MADRE") %>%
                    
                    mutate(
                      EDAD_MADRE = substring(EDAD_MADRE,11))) %>%
                
                select(EDAD_MADRE,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    
    neumo = map(.x =df,
                .f = ~svyby(~MOV_NEUMO_e1, by=~EDAD_MADRE, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_NEUMO_e1,vacunatipo = "NEUMO") %>% 
                  
                  select(-MOV_NEUMO_e1) %>% 
                  
                  left_join(
                  
                  svytotal(~EDAD_MADRE, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("EDAD_MADRE") %>%
                    
                    mutate(
                      EDAD_MADRE = substring(EDAD_MADRE,11))) %>%
                
                select(EDAD_MADRE,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    influ = map(.x =df,
                .f = ~svyby(~MOV_INFLU_e1, by=~EDAD_MADRE, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_INFLU_e1,vacunatipo = "INFLU") %>% 
                  
                  select(-MOV_INFLU_e1) %>% 
                  
                  left_join(
                  
                  svytotal(~EDAD_MADRE, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("EDAD_MADRE") %>%
                    
                    mutate(
                      EDAD_MADRE = substring(EDAD_MADRE,11))) %>%
                
                select(EDAD_MADRE,total,vacuna,vacunatipo,se,-`SE`)),
    
    
    rota  = map(.x =df,
                .f = ~svyby(~MOV_ROTA_e1, by=~EDAD_MADRE, design =.x, FUN=svytotal, na.rm = T) %>% 
                  
                  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA") %>% 
                  
                  select(-MOV_ROTA_e1) %>% 
                  
                  left_join(
                  
                  svytotal(~EDAD_MADRE, design = .x, na.rm = T) %>%
                    
                    data.frame() %>%
                    
                    rownames_to_column("EDAD_MADRE") %>%
                    
                    mutate(
                      EDAD_MADRE = substring(EDAD_MADRE,11))) %>%
                
                select(EDAD_MADRE,total,vacuna,vacunatipo,se,-`SE`))) %>% 
  
  
  mutate(
    
    pretotal1  = map2(.x = ptv, .y = neumo, .f = ~bind_rows(.x,.y)),
    pretotal2  = map2(.x = influ, .y = rota, .f = ~bind_rows(.x,.y)),
    
    total  = map2(.x = pretotal1, .y = pretotal2, .f = ~bind_rows(.x,.y)),
    
    hr = map(.x = total,
             .f = ~h_prop(.x)),
    
    ssirii = map(.x = total,
                 .f = ~sii_rii(.x)),
    
    
    graf = map(.x = hr,
               .f = ~gg(.x))
    
  ) 


# SII y RII por año (2010 - 2020)

  df3 %>% select(ANIO,ssirii) %>% 
  unnest(cols = c(ssirii)) %>% 
  as.data.frame() %>% 
  ungroup() %>% 
  mutate(
    rii.pct = (rii-1)*100
  ) %>% 
  
  pivot_longer(cols = c(rii.pct,ssi), names_to = "index") %>% 
  
  ggplot() +
  geom_line(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
  geom_point(aes(x = as.factor(ANIO), y = value, col = vacunatipo, group = vacunatipo)) +
  facet_wrap(~index)

# Grafico: tasa vs HR
ggsave("uu.png",cowplot::plot_grid(plotlist = df3$graf), width = 18, height = 15)


```