---
title: "Untitled"
output: html_document
---

```{r, warning=F, message=F,comment=F}

library(tidyverse)
library(survey)
library(jtools)
library(sandwich)
library(sf)
```

```{r}
# Base de trabajo
MOV_GENERAL <- read.csv("./BD.INTERMEDIAS/mov_general.csv")

df2<-MOV_GENERAL %>% 
  
  filter(!is.na(MOV_PTV_e1)) %>% 
  
  group_by(ANIO) %>% 
  nest() %>%
  mutate(
    df= map(.x = data, 
      .f = ~svydesign(id =~ V001, strata =~ V022, probs=~V005, data=.x))) 

options(survey.lonely.psu="remove")

```

# EVENTO

## DEPARTAMENTOS

```{r}
hr<-svyby(~MOV_PTV_e1_2, by=~DEPARTAMEN, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV") %>% 
  
  select(-MOV_PTV_e1_2) %>% 
  
  left_join(
    
      svytotal(~DEPARTAMEN, design = df) %>%
        
        data.frame() %>%
        
        rownames_to_column("DEPARTAMEN") %>%
        
        mutate(
          DEPARTAMEN = substring(DEPARTAMEN,11))) %>%
        
        select(DEPARTAMEN,total,vacuna,vacunatipo,se,-`SE`)



NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~DEPARTAMEN, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO") %>% 
  
  select(-MOV_NEUMO_e1_2) %>% 
  
  left_join(
    
      svytotal(~DEPARTAMEN, design = df) %>%
        
        data.frame() %>%
        
        rownames_to_column("DEPARTAMEN") %>%
        
        mutate(
          DEPARTAMEN = substring(DEPARTAMEN,11))) %>%
        
        select(DEPARTAMEN,total,vacuna,vacunatipo,se,-`SE`)




INFLU<-svyby(~MOV_INFLU_e1_2, by=~DEPARTAMEN, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU") %>% 
  
  select(-MOV_INFLU_e1_2) %>% 
  
  left_join(
    
      svytotal(~DEPARTAMEN, design = df) %>%
        
        data.frame() %>%
        
        rownames_to_column("DEPARTAMEN") %>%
        
        mutate(
          DEPARTAMEN = substring(DEPARTAMEN,11))) %>%
        
        select(DEPARTAMEN,total,vacuna,vacunatipo,se,-`SE`)



ROTA<-svyby(~MOV_ROTA_e1, by=~DEPARTAMEN, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA") %>% 
  
  select(-MOV_ROTA_e1) %>% 
  
  left_join(
    
      svytotal(~DEPARTAMEN, design = df) %>%
        
        data.frame() %>%
        
        rownames_to_column("DEPARTAMEN") %>%
        
        mutate(
          DEPARTAMEN = substring(DEPARTAMEN,11))) %>%
        
        select(DEPARTAMEN,total,vacuna,vacunatipo,se,-`SE`)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA) 


```

### Generando HR

```{r}
df2<-
  df2 %>% 
  group_by(vacunatipo) %>% 
  
  arrange(vacuna,.by_group = T) %>% 

  mutate(
    # casos por 10 000/habitantes
    tasa = (vacuna/total)*10000,
    pop= vacuna/sum(vacuna),
    popr = cumsum(pop)/sum(pop),
    pop.popr = popr - pop,
    hr2 = round((pop.popr + popr)/2,3)*100
    ) %>% 
  
  select(DEPARTAMEN,total,tasa,vacunatipo,hr2)

```

### Verificar

```{r}
ggplot(data = df2 , aes(x =hr2 , y = tasa)) +
  
  geom_point() +
  
  geom_smooth(method = "lm") +
  
  facet_wrap(~vacunatipo)
```

### SII y RII por vacuna

```{r}

bd <- data.frame(hr2 = c(0,1))

df2_n<-
  df2 %>% 
  
  #filter(DEPARTAMEN != "MADRE DE DIOS") %>% 
  
  group_by(vacunatipo) %>% 
  
  nest() %>% 
  
  mutate(
    
    modelo = map(.x = data, .f = ~lm(formula = tasa~hr2, data = .x)),
    
    modelo2 = map(.x = modelo, .f = ~tidy(lmtest::coeftest(.x, vcov = vcovHC, type = "HC2"), conf.int = T)),

    ) %>% 
  
  ungroup() %>% 
  
  unnest(cols = c(modelo2)) %>% 
  
  group_by(vacunatipo) %>% 
  
  slice(2) %>%
  
  mutate(rii = map_dbl(.x = modelo, 
                       .f =~predict(.x,newdata = bd %>% filter(hr2 == 1))/predict(.x,newdata = bd %>% filter(hr2 == 0))),
         
         ssi = round(estimate,2),
         rii = round(rii,3)) %>% 
  
  select(vacunatipo,term,ssi,rii)



```

## CRED LUGAR

```{r}
PTV<-svyby(~MOV_PTV_e1_2, by=~CREDLUGAR, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV") %>% 
  
  select(-MOV_PTV_e1_2) %>% 
  
  left_join(
    
      svytotal(~CREDLUGAR, design = df) %>%
        
        data.frame() %>%
        
        rownames_to_column("CREDLUGAR") %>%
        
        mutate(
          CREDLUGAR = substring(CREDLUGAR,10))) %>%
        
        select(CREDLUGAR,total,vacuna,vacunatipo,se,-`SE`)



NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~CREDLUGAR, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO") %>% 
  
  select(-MOV_NEUMO_e1_2) %>% 
  
  left_join(
    
      svytotal(~CREDLUGAR, design = df) %>%
        
        data.frame() %>%
        
        rownames_to_column("CREDLUGAR") %>%
        
        mutate(
          CREDLUGAR = substring(CREDLUGAR,10))) %>%
        
        select(CREDLUGAR,total,vacuna,vacunatipo,se,-`SE`)




INFLU<-svyby(~MOV_INFLU_e1_2, by=~CREDLUGAR, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU") %>% 
  
  select(-MOV_INFLU_e1_2) %>% 
  
  left_join(
    
      svytotal(~CREDLUGAR, design = df) %>%
        
        data.frame() %>%
        
        rownames_to_column("CREDLUGAR") %>%
        
        mutate(
          CREDLUGAR = substring(CREDLUGAR,10))) %>%
        
        select(CREDLUGAR,total,vacuna,vacunatipo,se,-`SE`)



ROTA<-svyby(~MOV_ROTA_e1, by=~CREDLUGAR, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA") %>% 
  
  select(-MOV_ROTA_e1) %>% 
  
  left_join(
    
      svytotal(~CREDLUGAR, design = df) %>%
        
        data.frame() %>%
        
        rownames_to_column("CREDLUGAR") %>%
        
        mutate(
          CREDLUGAR = substring(CREDLUGAR,10))) %>%
        
        select(CREDLUGAR,total,vacuna,vacunatipo,se,-`SE`)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA)

```

### Generando HR

```{r}
df2<-
  df2 %>% 
  group_by(vacunatipo) %>% 
  
  arrange(vacuna,.by_group = T) %>% 

  mutate(
    # casos por 10 000/habitantes
    tasa = (vacuna/total)*10000,
    pop= vacuna/sum(vacuna),
    popr = cumsum(pop)/sum(pop),
    pop.popr = popr - pop,
    hr2 = round((pop.popr + popr)/2,3)*100
    ) %>% 
  
  select(-se,-vacuna,-pop,-popr,-pop.popr)
```

### Verificar

```{r}
ggplot(data = df2 , aes(x =hr2 , y = tasa)) +
  
  geom_point() +
  
  geom_smooth(method = "lm") +
  
  facet_wrap(~vacunatipo)
```

### SII y RII por vacuna

```{r}
bd <- data.frame(hr2 = c(0,1))

df2<-
  df2 %>% 
  
  #filter(CREDLUGAR != "NoCRED") %>% 
  
  group_by(vacunatipo) %>% 
  
  nest() %>% 
  
  mutate(
    
    modelo = map(.x = data, .f = ~lm(formula = tasa~hr2, data = .x)),
    
    modelo2 = map(.x = modelo, .f = ~tidy(lmtest::coeftest(.x, vcov = vcovHC, type = "HC2"), conf.int = T)),

    ) %>% 
  
  ungroup() %>% 
  
  unnest(cols = c(modelo2)) %>% 
  
  group_by(vacunatipo) %>% 
  
  slice(2) %>%
  
  mutate(rii = map_dbl(.x = modelo, 
                       .f =~predict(.x,newdata = bd %>% filter(hr2 == 1))/predict(.x,newdata = bd %>% filter(hr2 == 0))),
         
         ssi = round(estimate,2),
         rii = round(rii,3)) %>% 
  
  select(vacunatipo,term,ssi,rii)


```

## EDUCACION DE LA MADRE

```{r}
PTV<-svyby(~MOV_PTV_e1_2, by=~EDU_MADRE, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV") %>% 
  
  select(-MOV_PTV_e1_2)


NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~EDU_MADRE, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO") %>% 
  
  select(-MOV_NEUMO_e1_2)


INFLU<-svyby(~MOV_INFLU_e1_2, by=~EDU_MADRE, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU") %>% 
  
  select(-MOV_INFLU_e1_2) 


ROTA<-svyby(~MOV_ROTA_e1, by=~EDU_MADRE, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA") %>% 
  
  select(-MOV_ROTA_e1)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA)

```

### Generando HR

```{r}
# df2<-
#   df2 %>%
#   group_by(vacunatipo) %>%
# 
#   arrange(vacuna,.by_group = T) %>%
# 
#   mutate(pop= vacuna/sum(vacuna),
# 
#          popr = cumsum(pop)/sum(pop),
#          pop.popr = popr - pop,
#          hr2 = round((pop.popr + popr)/2,3)
#          ) %>%
# 
#   select(-pop,-popr,-pop.popr)
```

### Verificar

```{r}
ggplot(data = df2 , aes(x =hr2 , y = vacuna)) +
  
  geom_point() +
  
  geom_smooth(method = "lm") +
  
  facet_wrap(~vacunatipo)
```

### SII y RII por vacuna

```{r}
# bd <- data.frame(hr2 = c(0,1))
# 
# df2<-
#   df2 %>% 
#   
#   group_by(vacunatipo) %>% 
#   
#   nest() %>% 
#   
#   mutate(
#     
#     modelo = map(.x = data, .f = ~lm(formula = vacuna~hr2, data = .x)),
#     
#     modelo2 = map(.x = modelo, .f = ~tidy(lmtest::coeftest(.x, vcov = vcovHC, type = "HC2"), conf.int = T)),
# 
#     ) %>% 
#   
#   ungroup() %>% 
#   
#   unnest(cols = c(modelo2)) %>% 
#   
#   group_by(vacunatipo) %>% 
#   
#   slice(2) %>%
#   
#   mutate(rii = map_dbl(.x = modelo, 
#                        .f =~predict(.x,newdata = bd %>% filter(hr2 == 1))/predict(.x,newdata = bd %>% filter(hr2 == 0))),
#          
#          ssi = estimate) %>% 
#   
#   select(vacunatipo,term,ssi,rii)
# 
# df2

ssi_rri(df2)

```

## INDICE RIQUEZA

```{r}
PTV<-svyby(~MOV_PTV_e1_2, by=~INDICERIQUEZA, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV") %>% 
  
  select(-MOV_PTV_e1_2)


NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~INDICERIQUEZA, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO") %>% 
  
  select(-MOV_NEUMO_e1_2)


INFLU<-svyby(~MOV_INFLU_e1_2, by=~INDICERIQUEZA, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU") %>% 
  
  select(-MOV_INFLU_e1_2) 


ROTA<-svyby(~MOV_ROTA_e1, by=~INDICERIQUEZA, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA") %>% 
  
  select(-MOV_ROTA_e1)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA)




```

### Generando HR

```{r}
df2<-
  df2 %>%
  group_by(vacunatipo) %>%

  arrange(vacuna,.by_group = T) %>%

  mutate(pop= vacuna/sum(vacuna),

         popr = cumsum(pop)/sum(pop),
         pop.popr = popr - pop,
         hr2 = round((pop.popr + popr)/2,3)
         ) %>%

  select(-pop,-popr,-pop.popr)

svytotal(~DEPARTAMEN, design = df) %>% data.frame() %>% rownames_to_column("DEPARTAMENTO")
```

### Verificar

```{r}
ggplot(data = df2 , aes(x =hr2 , y = vacuna)) +
  
  geom_point() +
  
  geom_smooth(method = "lm") +
  
  facet_wrap(~vacunatipo)
```

### SII y RII por vacuna

```{r}
# bd <- data.frame(hr2 = c(0,1))
# 
# df2<-
#   df2 %>% 
#   
#   group_by(vacunatipo) %>% 
#   
#   nest() %>% 
#   
#   mutate(
#     
#     modelo = map(.x = data, .f = ~lm(formula = vacuna~hr2, data = .x)),
#     
#     modelo2 = map(.x = modelo, .f = ~tidy(lmtest::coeftest(.x, vcov = vcovHC, type = "HC2"), conf.int = T)),
# 
#     ) %>% 
#   
#   ungroup() %>% 
#   
#   unnest(cols = c(modelo2)) %>% 
#   
#   group_by(vacunatipo) %>% 
#   
#   slice(2) %>%
#   
#   mutate(rii = map_dbl(.x = modelo, 
#                        .f =~predict(.x,newdata = bd %>% filter(hr2 == 1))/predict(.x,newdata = bd %>% filter(hr2 == 0))),
#          
#          ssi = estimate) %>% 
#   
#   select(vacunatipo,term,ssi,rii)

sii_rii(df2)
```

## EDAD MADRE

```{r}
PTV<-svyby(~MOV_PTV_e1_2, by=~EDAD_MADRE, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV") %>% 
  
  select(-MOV_PTV_e1_2)


NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~EDAD_MADRE, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO") %>% 
  
  select(-MOV_NEUMO_e1_2)


INFLU<-svyby(~MOV_INFLU_e1_2, by=~EDAD_MADRE, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU") %>% 
  
  select(-MOV_INFLU_e1_2) 


ROTA<-svyby(~MOV_ROTA_e1, by=~EDAD_MADRE, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA") %>% 
  
  select(-MOV_ROTA_e1)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA)

```

### Generando HR

```{r}
# df2<-
#   df2 %>%
#   group_by(vacunatipo) %>%
# 
#   arrange(vacuna,.by_group = T) %>%
# 
#   mutate(pop= vacuna/sum(vacuna),
# 
#          popr = cumsum(pop)/sum(pop),
#          pop.popr = popr - pop,
#          hr2 = round((pop.popr + popr)/2,3)
#          ) %>%
# 
#   select(-pop,-popr,-pop.popr)
```

### Verificar

```{r}
ggplot(data = df2 , aes(x =hr2 , y = vacuna)) +
  
  geom_point() +
  
  geom_smooth(method = "lm") +
  
  facet_wrap(~vacunatipo)
```

### SII y RII por vacuna

```{r}
# bd <- data.frame(hr2 = c(0,1))
# 
# df2<-
#   df2 %>% 
#   
#   #filter(CREDLUGAR != "NoCRED") %>% 
#   
#   group_by(vacunatipo) %>% 
#   
#   nest() %>% 
#   
#   mutate(
#     
#     modelo = map(.x = data, .f = ~lm(formula = vacuna~hr2, data = .x)),
#     
#     modelo2 = map(.x = modelo, .f = ~tidy(lmtest::coeftest(.x, vcov = vcovHC, type = "HC2"), conf.int = T)),
# 
#     ) %>% 
#   
#   ungroup() %>% 
#   
#   unnest(cols = c(modelo2)) %>% 
#   
#   group_by(vacunatipo) %>% 
#   
#   slice(2) %>%
#   
#   mutate(rii = map_dbl(.x = modelo, 
#                        .f =~predict(.x,newdata = bd %>% filter(hr2 == 1))/predict(.x,newdata = bd %>% filter(hr2 == 0))),
#          
#          ssi = estimate) %>% 
#   
#   select(vacunatipo,term,ssi,rii)
# 


ssi_rri(df2)
```

# EVENTO POR REGION

```{r}
PTV<-svyby(~MOV_PTV_e1_2, by=~INDICERIQUEZA + DEPARTAMEN, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_PTV_e1_2,vacunatipo = "PTV") %>% 
  
  select(-MOV_PTV_e1_2)


NEUMO<-svyby(~MOV_NEUMO_e1_2, by=~INDICERIQUEZA + DEPARTAMEN, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_NEUMO_e1_2,vacunatipo = "NEUMO") %>% 
  
  select(-MOV_NEUMO_e1_2)


INFLU<-svyby(~MOV_INFLU_e1_2, by=~INDICERIQUEZA + DEPARTAMEN, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_INFLU_e1_2,vacunatipo = "INFLU") %>% 
  
  select(-MOV_INFLU_e1_2) 


ROTA<-svyby(~MOV_ROTA_e1, by=~INDICERIQUEZA + DEPARTAMEN, design =df, FUN=svytotal) %>% 
  
  mutate(vacuna = MOV_ROTA_e1,vacunatipo = "ROTA") %>% 
  
  select(-MOV_ROTA_e1)



df2 <- bind_rows(PTV,NEUMO,INFLU,ROTA)

```

```{r}
h_prop.map(df2) %>% 
  
  ggplot(aes(x = hr2, y = vacuna)) +
  
  geom_point() + 
  
  geom_smooth(method = "lm") +
  
  facet_wrap(~vacunatipo + DEPARTAMEN)
```


```{r}
map.riqueza <- sii_rii_map(df2)
```


```{r}

# # Grafico lm
# ggplot(data = map.riqueza , aes(x =hr2 , y = casos.mov.ptv)) +
#   
#   geom_point() +
#   
#   geom_smooth(method = "lm") + 
#   
#   facet_wrap(~DEPARTAMEN)

```


```{r}
# map

gg<- 
  map.riqueza %>%
   
   left_join(region_shape, by = "DEPARTAMEN") %>% 
     
     st_as_sf() %>% 

   ggplot() +

   geom_sf(aes(fill = sii)) +

   theme_minimal() +

   labs(fill = "SII\nIR") +

   scale_fill_viridis_c(end = 0.7) +
     
     facet_wrap(~vacunatipo,nrow = 1) +
     
     theme_void() + 
     
     theme(legend.position="bottom")


gg 
#ggsave("gg.png",gg,height = 8,width = 15)
```

