---
title: "ssi_rri function"
output: html_document
---

# Preparacion de datos

```{r}
prep.data <-function(MOV2020){ MOV2020 %>%
  
  select(CASEID,
         # H1,H2,H3,H4,H5,H6,H7,H8,H9,H10,
         # S45D4,S45D5,S45P4,S45P5,S45B0,S45B1,
         # S45B2,S45B3,S45TT,S45SP1,S45SP2,S45SR,
         S45F1,S45F2,S45F3,
         S45PV1,S45PV2,S45PV3,
         S45NM1,S45NM2,S45NM3,
         S45RT1,S45RT2,
         S45IF1,S45IF2,
         
         S466,S466B,V001,V005,V012,V022,V023,
         V024,V025,V102,V106,V131,
         V481:V481X,V190,V022,ANIO,JUNTOS,V130) %>% 
  
  
  
  
        # cATEGORIAS DE RESPUESTA A LA VACUNACION
  mutate(
    
        # across(S45F1:S45IF2,~ifelse(.x == 0|.x == 8,0, # 0: No, 8: No sabe
        #                          ifelse(.x == 1|.x == 3,1,2))),# 1: Tarjeta fecha, # 3: Marca tarjeta
        
        
        across(S45F1:S45IF2,~ifelse(.x == 0|.x == 8,0,1)),# 1: Tarjeta fecha, # 3: Marca tarjeta

    
    
         
         CRED = as.factor(ifelse(S466==0 | S466 == 8,"No","Si")),
        
        
         
         S466B = ifelse(is.na(S466B),99,S466B),
         CREDLUGAR = factor(S466B, levels = c(21,22,23,24,
                                              25,26,27,31,
                                              32,41,42,96,99), labels = c("H.MINSA/FFAA","H.ESSALUD","H.MINSA/FFAA",
                                                                 "CS/POSTA MINSA","CS/POSTA MINSA","CS.ESSALUD",
                                                                 "OTRO/PRIVADO","OTRO/PRIVADO","OTRO/PRIVADO","OTRO/PRIVADO",
                                                                 "OTRO/PRIVADO","OTRO/PRIVADO","NoCRED")),
         
        
         
         
         TIPORESIDENCIA = ifelse(V102==1,"URBANO","RURAL"),
         
         
         
         
         
         DEPARTAMEN = factor(V024, levels = c(1:25), labels = c("AMAZONAS","ANCASH","APURIMAC","AREQUIPA","AYACUCHO",
                                                            "CAJAMARCA","CALLAO","CUSCO","HUANCAVELICA","HUANUCO",
                                                            "ICA","JUNIN","LA LIBERTAD","LAMBAYEQUE","LIMA",
                                                            "LORETO","MADRE DE DIOS","MOQUEGUA","PASCO","PIURA",
                                                            "PUNO","SAN MARTIN","TACNA","TUMBES","UCAYALI")),
         
         
         
         EDU_MADRE = as.factor(factor(V106, levels = c(0,1,2,3), labels = c("sin educ","primaria","secundaria","superior"))),
         
         
         ETNIA_MADRE = factor(V131, levels = c(1:12), labels = c("quechua","aimara","ashaninka","awajun",
                                                                 "shipibo","shawi","matsigenka","achuar",
                                                                 "Otro","castellano","portugues","Otro extranjero")),
        
        
        #REGIONNATURAL = factor(SREGION, levels = c(1,2,3,4), labels = c("limaMetro","Costa","Sierra","Selva")),
        
        #JUNTOS = factor(JUNTOS, levels =c(0,1), labels = c("No","Si")),
         
         
         
         #EDAD_ANIOS = round((QI478/12),0),
         
         SEGURO = factor(V481, levels = c(0,1), labels = c("No","Si")),
         
         EDAD_MADRE = ifelse(V012<18,"< 18 a",
                             ifelse(V012>=18&V012<30,"18-30 a",
                                    ifelse(V012>=30&V012<40,"30 a 40",
                                           ifelse(V012>=40,"40 a mas",NA)))),
         
         INDICERIQUEZA = factor(V190, levels = c(1:5), labels = c("1ro","2do","3ro","4to","5to")),
    
    
        V005 = V005/1000000) %>% 
  
  
  fastDummies::dummy_cols(select_columns = c("S45F1","S45F2","S45F3", # Hib
                                             "S45PV1","S45PV2","S45PV3", #Pentavalente
                                             "S45NM1","S45NM2","S45NM3", #Neumococo
                                             "S45IF1","S45IF2", #Influenza
                                             "S45RT1","S45RT2" # Rotavirus
                                             
                                             )) %>% 
  
   # CON CRED O SEGURO
   #filter((CRED == "Si" | SEGURO == "Si")) %>% 
  
  
  
  mutate( HIB_COMPLETA = as.factor(ifelse(S45F1 !=0 & S45F2 != 0 & S45F3 != 0,1,0)), # VACUNAS COMPLETAS
          PTV_COMPLETA = as.factor(ifelse(S45PV1 !=0 & S45PV2 != 0 & S45PV3 != 0,1,0)),
          NEUMO_COMPLETA = as.factor(ifelse(S45NM1 !=0 & S45NM2 != 0 & S45NM3 != 0,1,0)),
          INFLU_COMPLETA = as.factor(ifelse(S45IF1 !=0 & S45IF2 != 0,1,0)),
          ROTA_COMPLETA = as.factor(ifelse(S45RT1 !=0 & S45RT2 != 0,1,0)),
        
           ####
          ## Pentavalente
          MOV_PTV_e1 = ifelse(S45PV1==0,1,0),
          
          
          ## Neumococo 
          MOV_NEUMO_e1 = ifelse(S45NM1==0,1,0),
          
          
          ## Rotavirus (entre 2 y 4 meses, maximo 7 meses la 2da dosis)
          MOV_ROTA_e1 = ifelse(S45RT1 == 0,1,0),
          
          ## INFLUENZA (<12 m : 2 dosis, 12-35 meses:1 dosis, >36 meses: 1 dosis adulto)
          
          MOV_INFLU_e1 = ifelse(S45IF1 == 0,1,0))
          
}
```

#1. SII_RII

```{r}
h_prop<-
   function(data, level = NULL) {
           
   data<-      
      data %>% 
   group_by(vacunatipo) %>%  
    
    mutate(
       tasa = (vacuna/total)*10000
    ) %>% 
   
    # ordenar de - a +
   arrange(orden,.by_group = T) %>% 
   
     # Calculo de hr
   mutate(pop= vacuna/sum(vacuna),
          #tasa = (vacuna/total)*10000,
          popr = cumsum(pop)/sum(pop),
          pop.popr = popr - pop,
          hr2 = round((pop.popr + popr)/2,3)*100
          ) %>% 
   
   select(-pop,-popr,-pop.popr)
 
 
 data 
         }

```


```{r}
sii_rii<-function(data,level=NULL) {
   
   bd <- data.frame(hr2 = c(0,100))
   
  
       data<-
   data %>% 
   group_by(vacunatipo) %>%  
    
    mutate(
       tasa = (vacuna/total)*10000
    ) %>% 
   
    # ordenar de - a +
   #arrange(orden,.by_group = T) %>% 
   
     # Calculo de hr
   mutate(pop= vacuna/sum(vacuna),
          #tasa = (vacuna/total)*10000,
          popr = cumsum(pop)/sum(pop),
          pop.popr = popr - pop,
          hr2 = round((pop.popr + popr)/2,3)*100
          ) %>% 
   
   select(-pop,-popr,-pop.popr) %>% 
 
   
   group_by(vacunatipo) %>% 
   
   nest() %>% 
   
   mutate(
     
      # lm para ssi 
     modelo = map(.x = data, 
                  .f = ~lm(formula = tasa~hr2, data = .x, weights = total)),
     
      # extraer beta
     modelo2 = map(.x = modelo,
                   .f = ~broom::tidy(.x,conf.int = T))
 
     ) %>% 
   
   ungroup() %>% 
   
   unnest(cols = c(modelo2)) %>% 
   
   group_by(vacunatipo) %>% 
   
   slice(2) %>%
   
    # rri f(1)/f(0)
   mutate(
      rii = map_dbl(.x = modelo,
                .f =~predict(.x,
                             newdata = bd %>% filter(hr2 == 100))/predict(.x,newdata = bd %>% filter(hr2 == 0))),
      ssi = estimate,
      sii_l = conf.low,
      sii_h = conf.high
          ) %>% 
   
   select(vacunatipo,term,ssi,sii_l,sii_h)
 
 data
      }


```




#2. SII_RII MAPAS

```{r}
h_prop.map <-
   function(data) {

   data<-
      data %>% 
   group_by(DEPARTAMEN,vacunatipo) %>% 
      mutate(
         tasa = (vacuna/total)*10000 
      ) %>% 
   
    # ordenar de - a +
   arrange(orden,.by_group = T) %>% 
   
     # Calculo de hr
   mutate(pop= vacuna/sum(vacuna),
          
          popr = cumsum(pop)/sum(pop),
          pop.popr = popr - pop,
          hr2 = round((pop.popr + popr)/2,3)*100
          ) %>% 
   
   select(-pop,-popr,-pop.popr) %>% 
 
   
   group_by(DEPARTAMEN,vacunatipo) 
   
   data
   
}

```




#2. SII_RII MAPAS

```{r}
h_prop.map <-
   function(data) {

   data<-
      data %>% 
   group_by(DEPARTAMEN,vacunatipo) %>% 
      mutate(
         tasa = (vacuna/total)*100 
      ) %>% 
   
    # ordenar de - a +
   arrange(orden,.by_group = T) %>% 
   
     # Calculo de hr
   mutate(pop= vacuna/sum(vacuna),
          
          popr = cumsum(pop)/sum(pop),
          pop.popr = popr - pop,
          hr2 = round((pop.popr + popr)/2,3)
          ) %>% 
   
   select(-pop,-popr,-pop.popr) %>% 
 
   
   group_by(DEPARTAMEN,vacunatipo) 
   
   data
   
}
```


```{r}

sii_rii_map<-function(data) {
   
   
   bd <- data.frame(hr2 = c(0,100))
 

   data<-
      data %>% 
      
   group_by(DEPARTAMEN,vacunatipo) %>% 
      
      mutate(
         tasa = (vacuna/total)*100
      ) %>% 
   
    # ordenar de - a +
   arrange(orden,.by_group = T) %>% 
   
     # Calculo de hr
   mutate(pop= vacuna/sum(vacuna),
          
          popr = cumsum(pop)/sum(pop),
          pop.popr = popr - pop,
          hr2 = round((pop.popr + popr)/2,3)
          ) %>% 
   
   select(-pop,-popr,-pop.popr) %>% 
 
   
   group_by(DEPARTAMEN,vacunatipo) %>% 
   
   nest() %>% 
   
   mutate(
     
      # lm para ssi 
     modelo = map(.x = data, 
                  .f = ~lm(formula = tasa~hr2, weights = total, data = .x)),
     
      # extraer beta
     modelo2 = map(.x = modelo, 
                   .f = ~broom::tidy(.x, conf.int = T)),
 
     ) %>% 
   
   #ungroup() %>% 
   
   unnest(cols = c(modelo2)) %>% 
   
   slice(2) %>%
   
    # rri f(1)/f(0)
   mutate(rii = map_dbl(.x = modelo,
                        .f =~predict(.x,
                                     newdata = bd %>% filter(hr2 == 100))/predict(.x,newdata = bd %>% filter(hr2 == 0))),
          
          sii = estimate,
          sii_l = conf.low,
          sii_h = conf.high) %>% 
      
      mutate(sii = round(sii,2),
             rii = round(rii,1)) %>% 
   
   select(vacunatipo,term,sii,sii_l,sii_h)
 
 data
 
}
```

# grafico de verificación

```{r}
gg<-function(df2){ ggplot(data = df2 , aes(x =hr2 , y = tasa)) +
  
  geom_point() +
  
  geom_smooth(method = "lm") +
  
  facet_wrap(~vacunatipo)
   
}
```


```{r}
gg2<- function(data){ 
   
   ggplot(data = data, aes(fill=-sii)) + 
  geom_sf() +
  scale_fill_gradient2(mid="#FBFEF9",low="#0C6291",high="#A63446", limits=c(-19,19))+
      
      
      theme(
         axis.text.x = element_text(angle = 30, size = 6),
         strip.background = element_blank(),
         panel.background = element_blank(),
         strip.text = element_text(face = "bold"))+
      
      #theme_minimal()+
  facet_wrap(~ANIO, ncol = 6) 
   
}
```

